### ISSUE TITLE
[BUG]git submodule update (failed)

### ISSUE THREAD

**Issue by Emuuung** [jabbink/PokemonGoBot#239] opened 2016-07-24 21:51 UTC
**Description:**
Can't run `git submodule update` after `git clone`.

*log message*
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\PokemonGoBot\build.gradle' line: 71

* What went wrong:
A problem occurred evaluating root project 'pogo.scraper'.
> Could not resolve all dependencies for configuration 'detachedConfiguration3'.
   > Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
When I try again i get *log message*:
```
C:\PokemonGoBot>git submodule update --init --recursive
error: no such remote ref 282b8afb89d313e2697d3ee8fd0b0d0209ba6dd5
Fetched in submodule path 'lib/PokeGOAPI-Java', but it did not contain 282b8afb89d313e2697d3ee8fd0b0d0209ba6dd5. Direct fetching of that commit failed.
```

**Comment by RaeneDev** [comment] 2016-07-24 21:54
same Issue here. Tried the manual way too. :(

**Comment by Forty-Tw0** [comment] 2016-07-24 22:04
Yea, getting this as well...
I reverted #223 and my repo builds and runs.
https://github.com/Forty-Tw0/PokemonGoBot/tree/revert-223-spring-boot

**Comment by jabbink** [comment] 2016-07-24 22:05
Duplicate of #231 
And that one is fixed

**Comment by Forty-Tw0** [comment] 2016-07-24 22:06
Are you sure? I can't build your repo.

**Closed by jabbink** 2016-07-24 22:05 UTC

**Comment by Emuuung** [comment] 2016-07-24 22:06
I'm building latest and still nothing either.

**Comment by jabbink** [comment] 2016-07-24 22:07
Travis can build it, which wasn't possible before either.

To fix that I now require travis to give a green light, because *someone* clicked merge, even though travis told everyone that that stuff did not compile at all.

**Comment by jabbink** [comment] 2016-07-24 22:09
See here, the red crosses

![image](https://cloud.githubusercontent.com/assets/2461972/17086822/05532bb4-51fc-11e6-88ac-00891b386c03.png)

vs the green checkmarks

![image](https://cloud.githubusercontent.com/assets/2461972/17086824/0ea55426-51fc-11e6-86ea-5267370aa5ad.png)

**Comment by Forty-Tw0** [comment] 2016-07-24 22:10
Ok, master branch builds fine now. The develop branch was just behind. Thanks!

**Comment by Emuuung** [comment] 2016-07-24 22:10
Ah ok, then we'll wait for changes to be revert.
