### ISSUE TITLE
Stops working after 30 minutes 

### ISSUE THREAD

**Issue by Simpuhl** [jabbink/PokemonGoBot#230] opened 2016-07-24 20:25 UTC
**Description:**
Stops working after 30 minutes

**Steps to reproduce:**

1. Use it for 30 minutes

**Expected behavior:**
It should continue working after 30 mins

**Actual behavior:**
It stops working after 30 mins and just keeps trying to auth with google again

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
latest release 4

**Comment by megatixos** [comment] 2016-07-24 20:36
There is a 5th release now.. try using that.

**Comment by Simpuhl** [comment] 2016-07-24 20:44
Sorry I meant using release 5

Ill run it some more and see if it still does it

**Comment by jabbink** [comment] 2016-07-24 21:16
Release v0.4.0 is the 5th release. You're both right.

**Comment by jabbink** [comment] 2016-07-24 22:25
Also duplicate of #165 which is apparently not fixed

**Closed by jabbink** 2016-07-24 22:25 UTC
