### ISSUE TITLE
[Bug in 0.4.1] Error when restart the bot (for a new location)

### ISSUE THREAD

**Issue by casper-gh** [jabbink/PokemonGoBot#271] opened 2016-07-25 04:45 UTC
**Description:**
Since the bot does not support multiple locations, I had to create some cron entries which modifies the config file for a new GPS coordinates every 5 minutes. 

So basically I just terminate the running program using `pkill -f bot.jar` and re-run the program with modified config file. It worked in older version, but in 0.4.1, I got an error and the program halts forever.

**Steps to reproduce:**

1. Run the bot
2. Kill the bot using `pkill -f bot-jar-file-name.jar`
3. Edit the config file for new location (close by)
4. Re-run the bot

**Expected behavior:**
Should see the logs.

**Actual behavior:  (not everything)**
```
04:28:01.357 [Thread-6] INFO org.springframework.context.annotation.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1ae4b3b8: startup date [Mon Jul 25 04:24:01 UTC 2016]; root of context hierarchy
04:28:01.357 [Thread-6] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
04:28:01.357 [Thread-6] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@28f270bc: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,main,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor,botRunService,botConfiguration,httpClient,org.springframework.boot.autoconfigure.AutoConfigurationPackages]; root of factory hierarchy
```

**Version:**
0.4.1

**Comment by MrJokerer** [comment] 2016-07-25 05:04
same thing happened to me except i was just closing out of the bot changing something in config and relaunching it.

**Comment by ursalame** [comment] 2016-07-25 05:18
Open your config file under /bot-settings/*.json
Make sure that the JSON is properly formatted.

Paste it here if you need help.

**Comment by casper-gh** [comment] 2016-07-25 05:22
@ursalame So the config is moved to /bot-settings/ folder?

**Comment by PalletTownHero** [comment] 2016-07-25 05:23
@ursalame I get a similar error when attempting to change settings in the config file. Tried deleting 
the token and restarting the bot however I get this after

`{
  "name" : "config-properties-conversion",
  "startingLatitude" : 34.00887939596222,
  "startingLongitude" : -118.48673995034731,
  "credentials" : {
    "type" : "google"
  }`

^ Current (after deleting the token)

`Caused by: java.lang.IllegalArgumentException: No save file found for name: .DS_Store`

Error upon restart

@casper-gh It creates the json file (which has some more settings in it) after your first run of the program. My problem is any time I try to change it by stopping the bot -> changing json -> restarting I get some errors

**Comment by casper-gh** [comment] 2016-07-25 05:26
@PalletTownHero that explains...

But when we restart the bot, isn't it suppose to create a new json file in `bot-settings/` based on the new config.properties?

**Comment by ursalame** [comment] 2016-07-25 05:31
@PalletTownHero 

Here is how your JSON should look like:

```
{
  "name" : "config-properties-conversion",
  "startingLatitude" : 34.0088793,
  "startingLongitude" : -118.4867399,
  "credentials" : {
    "type" : "google",
    "token" : ""
  },
  "speed" : 2.778,
  "shouldDropItems" : true,
  "preferredBall" : "ITEM_POKE_BALL",
  "shouldAutoTransfer" : true,
  "shouldDisplayKeepalive" : true,
  "shouldDisplayWalkingToNearestUnused" : true,
  "shouldDisplayPokestopSpinRewards" : true,
  "shouldDisplayPokestopName" : true,
  "shouldDisplayPokemonCatchRewards" : true,
  "shouldHatchEggs" : true,
  "keepPokemonAmount" : 1,
  "desiredCatchProbability" : 0.8,
  "transferIVThreshold" : 80,
  "transferCPThreshold" : 1000,
  "ignoredPokemon" : [ "EEVEE", "MEWTWO", "MEW", "VAPOREON" ],
  "obligatoryTransfer" : [ "PIDGEY" ],
  "walkOnly" : false,
  "sortByIV" : false,
  "uselessItems" : {
    "ITEM_REVIVE" : 20,
    "ITEM_MAX_REVIVE" : 10,
    "ITEM_POTION" : 0,
    "ITEM_SUPER_POTION" : 0,
    "ITEM_HYPER_POTION" : 30,
    "ITEM_MAX_POTION" : 50,
    "ITEM_POKE_BALL" : 50,
    "ITEM_GREAT_BALL" : 50,
    "ITEM_ULTRA_BALL" : 50,
    "ITEM_MASTER_BALL" : 50,
    "ITEM_RAZZ_BERRY" : 50
  }
}
```

**Comment by PalletTownHero** [comment] 2016-07-25 05:31
@casper-gh Forgive me if its obvious, I'm a noob lol.

Deleting the bot-settings folder entirely and re-authenticating through google.com/device with generated code gets it running, however the properties are not transferring over completely and correctly,
always keep and always toss pokemon are transferred over but the lines like transfer CP threshold and useless items don't. Not sure why.

**Comment by PalletTownHero** [comment] 2016-07-25 05:33
@ursalame Thanks! I formatted it wrong :o 👍

**Comment by casper-gh** [comment] 2016-07-25 05:37
@ursalame Is this file auto-generated? if I want to edit the coordinates, should I edit `config.properties` or `bot-settings/config-properties-conversion.json` ?

**Comment by ursalame** [comment] 2016-07-25 05:40
The file should be generated but try creating your own with the JSON file I posted.

To change your coordinates you need to edit `bot-settings/config-properties-conversion.json`

**Comment by PalletTownHero** [comment] 2016-07-25 05:41
@casper-gh @ursalame Removing whatever is between the token : "" along with edits to the parameters seems to work. Thanks for your help! :)

**Comment by casper-gh** [comment] 2016-07-25 05:48
@ursalame @PalletTownHero So what if I just delete the entire `-settings/config-properties-conversion.json`, would the bot regenerates a new one when it restarts?

I don't want to rewrite my script to edit coordinates on the fly.

**Comment by PalletTownHero** [comment] 2016-07-25 06:08
@casper-gh I found you don't need to delete it, simply delete anything between the quotes from the token 

`{
  "name" : "config-properties-conversion",
  "startingLatitude" : xxxxxxxxx,
  "startingLongitude" :xxxxxxxx,
  "credentials" : {
    "type" : "google",
    "token" : _"anything in here"_
  },`

**Comment by casper-gh** [comment] 2016-07-25 06:47
@PalletTownHero Thanks, but deleting a folder only needs a simple command.

Still got some other errors and the bot keeps going back to the same pokestop, anyway I'm going back to .3.0, seems very stable for me

**Comment by jabbink** [comment] 2016-07-25 09:09
Issue is fixed because the JSON thingy is gone again

**Closed by jabbink** 2016-07-25 09:09 UTC
