### ISSUE TITLE
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null

### ISSUE THREAD

**Issue by KyleBoyer** [jabbink/PokemonGoBot#608] opened 2016-07-28 22:34 UTC
Stack trace:

com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.pokemon.Pokemon.transferPokemon(Pokemon.java:106)
	at ink.abb.pogo.scraper.tasks.ReleasePokemon.run(ReleasePokemon.kt:46)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:116)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
	... 9 more

**Comment by casper-gh** [comment] 2016-07-28 22:37
I think we're getting same error:

```
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at ink.abb.pogo.scraper.Bot.start(Bot.kt:89)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:128)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 5 more
```

Maybe Niantic updated their API and blocking all Bots/Maps?

**Comment by xenxes** [comment] 2016-07-28 22:37
Having issues with all tools using pokegoAPI, now getting unexpected errors logging in (all versions including latest commit). Something definitely got patched.

https://www.reddit.com/r/pokemongodev/comments/4v36h5/is_traffic_being_throttled/

**Comment by kasagon** [comment] 2016-07-28 22:41
@xenxes I also think they are getting something patched, all the Errors I get are errors at com.pokegoapi.*

Those errors includes:

- Logging in Error
- Error running loop ProfileLoop!
- Error running loop BotLoop!
- Error running loop WalkLoop!
- Failed to transfer [Pokemon]: FAILED

**Comment by husbeard** [comment] 2016-07-28 22:42
I think we all got soft banned. Someone on a reddit forum was talking about trying to find out the extra data being sent by some users in the headers. They think they were bots, and might have patched it.

**Comment by xenxes** [comment] 2016-07-28 22:47
*need to throttle requests to 3 per second*

**Comment by casper-gh** [comment] 2016-07-28 22:51
FYI logging into Emulator/phone, looting pokestops, and catching pidgey still work...so no ban

**Comment by husbeard** [comment] 2016-07-28 22:53
Yeah, it looks like they figured out something with the bot for now. We'll have to wait for the actual brains of this operation to fix it. ;)

**Comment by casper-gh** [comment] 2016-07-28 22:54
People on Reddit are saying it will work if we only send 3 request/sec.

**Comment by husbeard** [comment] 2016-07-28 22:54
How are we able to edit the requests per second in the config.properties?

**Comment by ZeeSteen** [comment] 2016-07-28 22:57
@husbeard you can't. It'll be changed in the code :) - BTW I'm interested at being a contributor ! Dunno if there's a process to becoming one :p it'd be my first open source project :p

**Comment by Emuuung** [comment] 2016-07-28 22:59
We can't confirm this, servers are very unstable right now if you look theirs status.

**Comment by husbeard** [comment] 2016-07-28 22:59
@ZeeSteen - Thanks for the explanation.

**Comment by kasagon** [comment] 2016-07-28 23:04
Is it possible that they throttle the incoming data to the server to reduce the server stress?
Like, today was not really the best day a server can have.

**Comment by ansalls** [comment] 2016-07-28 23:07
I've got the same error, though it seems to be playing fine through the errors on version 3.0. It's catching and collecting stops.

**Comment by marekkobida** [comment] 2016-07-28 23:17
@ZeeSteen Where in code I can change this?

**Comment by Loewe1000** [comment] 2016-07-28 23:33
@marekkobida 
It is not just a single line of code you can change.
We would need to rewrite almost the complete structure of the bot, so there are not so many requests per second, because every "loop" is independend, so they will send request independently.

**Comment by jaredkwright** [comment] 2016-07-28 23:41
I'm thinking maybe create a central task queue and every loop can just throw things onto the queue and the task manager or whatever you want to call it can be responsible for making sure they are timed appropriately. If I can get this building I may take a stab at it, although I haven't really done any Kotlin.

**Comment by karael** [comment] 2016-07-28 23:44
@jaredkwright is right you need to implement a queue

**Comment by Akkadius** [comment] 2016-07-29 00:21
Queue can solve this issue, but I feel like this is just the beginning of them tightening up holes. There are so many ways they could be detecting non-mobile client sessions and shutting them down.

**Comment by russr123** [comment] 2016-07-29 01:01
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 20:59:49: Server returned unexpected error
28 Jul 20:59:49: Retrying...
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
28 Jul 20:59:50: Server returned unexpected error

**Comment by aTadTasty** [comment] 2016-07-29 01:06
i'm having the same `Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at ink.abb.pogo.scraper.Bot.start(Bot.kt:89)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:128)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
` error.

**Comment by cq65617875** [comment] 2016-07-29 01:55
i think when found and catching pokemon
system need stop walking loop wait the catch complete

**Comment by Rishabhpatted24** [comment] 2016-07-29 01:56
was just about to post this...!! damn

**Comment by aTadTasty** [comment] 2016-07-29 02:41
@cq65617875 that shouldn't matter though. i think it's just about how quickly the packets are being sent. I reduced my internet latency and ping down by 700ms and it seems to work flawlessly again.

Imagine you are in an actual game, you would click on a pokemon, and still be driving, so the walking is independent on the catching and the actual location of the pokemon, unless you walked away tooo tooo too far, which is very unlikely.

**Comment by wgleiuni** [comment] 2016-07-29 02:50
@russr123 got the same error with you. Have you found any solution?

**Comment by cq65617875** [comment] 2016-07-29 02:50
@aTadTasty 
yes, when i task 3 process used pokeapi at the same time
like catch/drop/hatchegg
pokeapi will throw the InvalidProtocolBufferException
i think pokeapi limited the packets count at one time
so we just limit the number of packets 
it will be work flawlessly :)

**Comment by cq65617875** [comment] 2016-07-29 03:26
foolish way :
iptables -A OUTPUT -p tcp -d 130.211.14.80/32 -m limit --limit 3/sec --limit-burst 5 -j ACCEPT
iptables -A OUTPUT -p tcp -d 130.211.14.80/32 -j DROP

**Comment by pvase666** [comment] 2016-07-29 03:31
29 Jul 10:30:34: Error running loop BotLoop!
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:177)
        at ink.abb.pogo.scraper.gui.SocketServer.sendPokestop(SocketServer.kt:106)
        at ink.abb.pogo.scraper.tasks.Walk.run(Walk.kt:47)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:54)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:177)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:118)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:32)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:139)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:32)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:175)
        ... 10 more


I got same error when run the bot for 3 hours :(

**Comment by iamthasasquatch** [comment] 2016-07-29 03:52
everyone who works on developing the bot is currently asleep you have to wait until they update it to add a delay in transmissions. currently niantic are dropping any spammy transmissions

**Comment by siimveskilt** [comment] 2016-07-29 05:42
As a temp hack I just added Thread.sleep(350) to some places.. like the task loop and walking loop and now botting like normal :) Start by sandwhiching the task loop with 200ms delays and then experiment to see after what actions to slow down (transfer, profileloop, walkingloop) also.

**Comment by casper-gh** [comment] 2016-07-29 05:42
Somehow the bots start to run again...

**Comment by aTadTasty** [comment] 2016-07-29 05:46
@casper-gh mine still does not work unless i lower my internet latency by at least 300ms

**Comment by okynk** [comment] 2016-07-29 06:04
@siimveskilt i tried your hack, the bot could walk & get pokestop but didn't catch any pokemon, do you know why?

**Comment by cq65617875** [comment] 2016-07-29 06:06
@okynk do u saw the log said 
"Pausing to catch pokemon..."

**Comment by okynk** [comment] 2016-07-29 06:09
@cq65617875 nope.. only "getting map of.." & pokestop

**Comment by siimveskilt** [comment] 2016-07-29 06:16
@okynk Without knowing what you changed it's hard to say.

**Comment by okynk** [comment] 2016-07-29 06:20
@siimveskilt i only add `Thread.sleep(300)` on some places around `task(something)` and inside `runLoop`
which commit you use on PokeGoAPI library? is it the latest on development?

**Comment by siimveskilt** [comment] 2016-07-29 06:21
@okynk Yes, latest. I could take a look if you could upload the files you changed and your config file in e.g 
pastebin.

**Comment by okynk** [comment] 2016-07-29 06:27
@siimveskilt
http://pastebin.com/Q5hG9fa3

**Comment by pashorizer** [comment] 2016-07-29 22:31
The walking bug will be fixed here https://github.com/jabbink/PokemonGoBot/pull/574

**Comment by langerhans** [comment] 2016-07-30 18:05
Should be fixed in v0.5.0-alpha3

**Closed by langerhans** 2016-07-30 18:05 UTC

**Comment by timchen100** [comment] 2016-08-01 20:16
Getting this error on alpha4.

```
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:77)
        at com.pokegoapi.api.player.PlayerProfile.getPlayerData(PlayerProfile.java:227)
        at ink.abb.pogo.scraper.Bot.start(Bot.kt:59)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:148)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(Requ
```

**Comment by matholland618** [comment] 2016-08-03 20:07
I got this for the first time today on alpha 4

**Comment by husbeard** [comment] 2016-08-03 20:30
Servers are currently down, which is why you're getting the Contents of buffer are null error.

**Comment by matholland618** [comment] 2016-08-03 20:31
Ahhh, gotcha!  Makes since!  I forgot to check that :P  Thanks!!
