### ISSUE TITLE
pogo.scraper-all-0.5.0-alpha2 Startup Error (Unknown Source)

### ISSUE THREAD

**Issue by Simpuhl** [jabbink/PokemonGoBot#614] opened 2016-07-29 00:30 UTC
**Description:**
Starting the bot using java -jar pogo.scraper-all-0.5.0-alpha2.jar just causes this error and it closes:

![image](https://cloud.githubusercontent.com/assets/262571/17233929/e9e33d3e-54e8-11e6-8ede-bc44d5b61a91.png)

**Comment by Agronis** [comment] 2016-07-29 00:34
All APIs are currently down until request times are buffered.

**Comment by Simpuhl** [comment] 2016-07-29 00:37
@Agronis 

Thank you for the reply. Out of curiosity do we have any ETA?

**Comment by Agronis** [comment] 2016-07-29 00:39
Those with merge perms are in bed for the evening.

There has been a hotfix to the PokeGoAPI seen [here](https://github.com/Grover-c13/PokeGOAPI-Java/pull/328).

You should be able to pull down the submodule and build from source.

Whether it's a fix ALL around - I cannot say.

**Comment by Simpuhl** [comment] 2016-07-29 00:43
@Agronis 

Thank you for the info, I will try this. If not ill just wait for the people with merge permissions to try and test and wait for a new release

**Comment by Emuuung** [comment] 2016-07-29 02:09
@Agronis Have you tried it? it was merged to Development branch of the PokeGOAPI-Java, so I tried building from source and got same error. Does it work for you?

**Comment by Agronis** [comment] 2016-07-29 02:16
No, as expected - it does not.

The current hotfix only slows down requests for one aspect of the API.

Most of which will have to be rebuilt.

**Comment by Simpuhl** [comment] 2016-07-29 02:33
So we are probably screwed for a while then, lol

**Comment by edommoner** [comment] 2016-07-29 02:35
if your error is "java.lang.StackOverflowError" then try command

java -jar -Xss2048k pogo.scraper-all-0.5.0-alpha2.jar.

**Comment by Emuuung** [comment] 2016-07-29 03:17
The hot fix worked for login, but for every other functionality in this repository the requests go much faster (walking, catching pokemon, looting pokestops, etc), will have to wait for a fix in the PokeGOAPI-Java, tho they are expecting this to be a temporary issue that happened a few weeks before, if it persists then they will get working on it.

**Comment by langerhans** [comment] 2016-07-29 06:58
Duplicate of #582

**Closed by langerhans** 2016-07-29 06:58 UTC
