### ISSUE TITLE
Suggestion: Stay at Lure Module for...

### ISSUE THREAD

**Issue by Shazgul** [jabbink/PokemonGoBot#747] opened 2016-08-02 07:21 UTC
Since i'm new to GitHub i don't know how to post Suggestions here (or if i'm even allowed to), but maybe it's possible for you guys to implement the feature that the bot stays at lure modules for like xxx Minutes until going to next pokestop?

**Comment by jabbink** [comment] 2016-08-02 07:49
Will be implemented in #728 as far as I know.

**Comment by jabbink** [comment] 2016-08-03 14:42
Also duplicate of #54

**Closed by jabbink** 2016-08-03 14:42 UTC
