### ISSUE TITLE
error message popup then the whole night hang there

### ISSUE THREAD

**Issue by zhoushifeng8** [jabbink/PokemonGoBot#1327] opened 2016-11-19 04:14 UTC
**Description:**
19 十一月 01:19:23 [default: BotLoop] - Found pokemon PINSIR
19 十一月 01:19:24 [default: WalkingLoop] - Pausing to catch pokemon...
Exception in thread "RxComputationScheduler-4" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException: Invalid Auth status code received, token not refreshed?
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:374)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:371)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:204)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
	at rx.internal.operators.OnSubscribeTimerOnce$1.call(OnSubscribeTimerOnce.java:49)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:186)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: ink.abb.pogo.api.exceptions.LoginFailedException: Invalid Auth status code received, token not refreshed?
	at ink.abb.pogo.api.network.ActionQueue.sendRequests(ActionQueue.kt:161)
	at ink.abb.pogo.api.network.ActionQueue.access$sendRequests(ActionQueue.kt:26)
	at ink.abb.pogo.api.network.ActionQueue$1$1.invoke(ActionQueue.kt:75)
	at ink.abb.pogo.api.network.ActionQueue$1$1.call(ActionQueue.kt:26)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
	... 10 more
19 十一月 01:19:29 [default: WalkingLoop] - Pausing to catch pokemon...
19 十一月 01:19:34 [default: WalkingLoop] - Pausing to catch pokemon...
19 十一月 01:19:36 [default: PokestopLoop] - Looting nearby pokestop ab6e3ca42796448ab7a00f8faec55d2a.16
19 十一月 01:19:52 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 02:20:47 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 03:21:42 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 05:22:32 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 06:23:26 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 07:24:21 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 08:25:16 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 09:26:10 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 10:27:05 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2
19 十一月 11:28:00 [default: ProfileLoop] - Stack of pokemon ready to evolve: 1/2

**Steps to reproduce:**

1. [Step 1]
2. [Step 2]

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[What actually happens]

**Stacktrace (If it's a crash):**
1.0.1

**Version:**
[The version of the bot you used; when self-compiled: :exclamation: the commit hash :exclamation:]

**Operating System:**
MAC

**Java version:**
[Full output of `java -version`]

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by Sieberkev** [comment] 2016-11-19 10:51
Duplicate of #1324

**Closed as completed by Sieberkev** 2016-11-19 10:51 UTC
