### ISSUE TITLE
execution failed for task ':run'

### ISSUE THREAD

**Issue by TheJ0k3r** [jabbink/PokemonGoBot#632] opened 2016-07-29 11:53 UTC
This is what happened to me when i ran the last build i don't realy know how it happaned. I can log in but then it crashes

like this
![knipsel1236](https://cloud.githubusercontent.com/assets/14089467/17247660/02a39b46-5595-11e6-94bf-96b206af7646.PNG)

I did all these steps
|-Clone this repo: `git clone

||-Run `git submodule update --init --recursive`

|||-Run from terminal/cmd: `gradlew build`

||||-Rename `./config.properties.template` to `./config.properties`

|||||-Modify `config.properties` as you please

||||||-To run the bot directly from console run `gradlew run`

**Stacktrace**
http://pastebin.com/PSd1rrGx 

**Version:**
latest on 29-07-2016 13:50

**Operating System:**
windows 10 pro

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by Sieberkev** [comment] 2016-07-29 11:57
Duplicate of #627

**Comment by pashorizer** [comment] 2016-07-29 12:01
Quick fix for that https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt#L91-L98

Use try-catch there

```
 do {
        try {
                reply = api.map.mapObjects
                Log.normal("Got ${reply.pokestops.size} pokestops")
                if (reply == null || reply.pokestops.size == 0) {
                    Log.red("Retrying in $sleepTimeout seconds...")
                    Thread.sleep(sleepTimeout * 1000)
                }
            } catch (e : Exception){}
        } while (reply == null || reply.pokestops.size == 0)
```

**Comment by langerhans** [comment] 2016-07-29 12:07
Duplicate, closing.

**Closed by langerhans** 2016-07-29 12:07 UTC

**Comment by TheJ0k3r** [comment] 2016-07-29 12:10
its not anout the 

> Contents of buffer are null

 you refering to 

my problem is about the

>  execution failed for task run

**Comment by Sieberkev** [comment] 2016-07-29 12:14
The fix provided by @pashorizer will let the task "run" (in fact is it a build + run, and the run part fails here) pass, but running it will still throw a LOT of exceptions.

**Comment by karael** [comment] 2016-07-29 12:25
Try to go to /lib/pokemonjavaapi (something like this) and git pull origin Development

**Comment by TheJ0k3r** [comment] 2016-07-29 12:37
can't find it
