### ISSUE TITLE
Always shooting the perfect shot?

### ISSUE THREAD

**Issue by masiarb** [jabbink/PokemonGoBot#82] opened 2016-07-22 18:01 UTC
Hi everyone,

Thanks for the great tool. I noticed each time the bot captures a pokemon it gets a perfect shot (with all the bonuses), is that right? Isn't this giving a bit away who is using the bot? Shouldn't the capture be random?

**Comment by CosmoRing** [comment] 2016-07-22 18:32
I thought the same thing. I guess someone could add configuration for that on the config file.

**Comment by pr0ves** [comment] 2016-07-23 20:45
Closing because duplicate of #70

**Closed by pr0ves** 2016-07-23 20:45 UTC
Labels: duplicate
