### ISSUE TITLE
GoogleLogin: Refreshed Token

### ISSUE THREAD

**Issue by neox387** [jabbink/PokemonGoBot#291] opened 2016-07-25 09:48 UTC
**Description:**
Bunch of spam with: 'Refreshed token' ending in below error, but the bot does continue normally afterwards

**Steps to reproduce:**

1. Run bot 0.4.2 for some time, 30 mins ?

**Stacktrace (If it's a crash):**
D/RequestHandler: Refreshing Token
D/GoogleLogin: Refreshed Token xxxxxxxx
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
D/RequestHandler: Authenticated with static token
Exception in thread "Thread-446" java.util.ConcurrentModificationException
Looting nearby pokestop 99ac8cc2fe9b464b9ddf5bacdbafb8a4.16
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
        at java.util.ArrayList$Itr.next(Unknown Source)
        at com.pokegoapi.api.map.MapObjects.update(MapObjects.java:198)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:312)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:250)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:185)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:175)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:101)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:23)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:97)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:83)
        at ink.abb.pogo.scraper.Bot$run$$inlined$fixedRateTimer$lambda$lambda$2.invoke(Bot.kt:25)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
Prebuilt 0.4.2

**Comment by jabbink** [comment] 2016-07-25 09:53
Duplicate of #165

**Closed by jabbink** 2016-07-25 09:53 UTC
