### ISSUE TITLE
Anyway to run the bot again without restarting computer?

### ISSUE THREAD

**Issue by IgnitEngineer** [jabbink/PokemonGoBot#1175] opened 2016-08-19 12:43 UTC
Hey guys, whenever i stop running the bot and try to start it again, this is what happens:

> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:104)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:61)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	... 3 more
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:186)
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer.start(UndertowEmbeddedServletContainer.java:121)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at ink.abb.pogo.scraper.MainKt.main(Main.kt:89)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:142)
	... 19 more

I just want to know if anyone knows how to fix this without restarting computer?
I try to use lsof to find the ports to kill but there ware too many!

**Comment by jabbink** [comment] 2016-08-19 12:45
Hi @IgnitEngineer,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-21 14:45) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by MacDogg** [comment] 2016-08-19 13:20
_Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use_
The fix for this is to change your port in the config file or by launching the bot with a switch.  I'll have to check for the exact code...

**Comment by Sieberkev** [comment] 2016-08-19 13:42
[FAQ](https://github.com/jabbink/PokemonGoBot/blob/develop/FAQ.md#i-get-address-already-in-use)

**Comment by Taraegon** [comment] 2016-08-19 13:49
You probably have Windows. On the off chance you run OSX: Ctrl-C in your Terminal. Then open your Monitor. You can find that in the Utilities folder. Look for the Java process. Force quit. In Terminal relaunch your bot. Enjoy.

**Comment by Muwai** [comment] 2016-08-21 02:05
@IgnitEngineer 

Type this into Terminal:

lsof -n -i4TCP:8080

Now type: kill -9 PID

PID = the Process ID that the first command gave you.

Now type the regular command: java -jar PokemonGoBot-0.6.0.jar

It happens to me when my Mac is using a Java process such as Oldschool Runescape. Works every time.

**Comment by patzor** [comment] 2016-08-21 09:54
or when in terminal just do:

killall -9 java

#but make sure there is no other java running aside from bot :P cheers

**Comment by jabbink** [comment] 2016-08-22 12:50
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.

**Closed by jabbink** 2016-08-22 12:50 UTC
Labels: incomplete issue
