### ISSUE TITLE
Can't Get my bot to launch

### ISSUE THREAD

**Issue by ItsFletch** [jabbink/PokemonGoBot#853] opened 2016-08-08 16:26 UTC
Getting this when i try and launch the bot. Any help would be appreciated. Thanks

C:\Users\Danny\Desktop\New folder>start cmd /c cd desktop/new folder   && java -
jar PokemonGoBot-0.5.0.jar

2016-08-08 17:21:43.224  INFO 8652 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : Starting MainKt on Dannys-PC with PID 8652 (C:\Users\Danny\D
esktop\New folder\PokemonGoBot-0.5.0.jar started by Danny in C:\Users\Danny\Desk
top\New folder)
2016-08-08 17:21:43.227  INFO 8652 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : No active profile set, falling back to default profiles: def
ault
2016-08-08 17:21:43.272  INFO 8652 --- [           main] ationConfigEmbeddedWebA
pplicationContext : Refreshing org.springframework.boot.context.embedded.Annotat
ionConfigEmbeddedWebApplicationContext@506c589e: startup date [Mon Aug 08 17:21:
43 BST 2016]; root of context hierarchy
2016-08-08 17:21:44.264  INFO 8652 --- [           main] org.xnio
                  : XNIO version 3.3.6.Final
2016-08-08 17:21:44.278  INFO 8652 --- [           main] org.xnio.nio
                  : XNIO NIO Implementation Version 3.3.6.Final
2016-08-08 17:21:44.416  WARN 8652 --- [           main] io.undertow.websockets.
jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo
, the default worker will be used
2016-08-08 17:21:44.416  WARN 8652 --- [           main] io.undertow.websockets.
jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo
, the default pool will be used
2016-08-08 17:21:44.429  INFO 8652 --- [           main] io.undertow.servlet
                  : Initializing Spring embedded WebApplicationContext
2016-08-08 17:21:44.430  INFO 8652 --- [           main] o.s.web.context.Context
Loader            : Root WebApplicationContext: initialization completed in 1160
 ms
2016-08-08 17:21:44.573  INFO 8652 --- [           main] o.s.b.c.e.ServletRegist
rationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-08 17:21:44.577  INFO 8652 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-08 17:21:44.578  INFO 8652 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-08 17:21:44.578  INFO 8652 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-08-08 17:21:44.578  INFO 8652 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-08-08 17:21:44.836  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.cont
ext.embedded.AnnotationConfigEmbeddedWebApplicationContext@506c589e: startup dat
e [Mon Aug 08 17:21:43 BST 2016]; root of context hierarchy
2016-08-08 17:21:44.885  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bots]}" onto public final java.util.List<ink.
abb.pogo.scraper.Settings> ink.abb.pogo.scraper.controllers.BotController.bots()

2016-08-08 17:21:44.887  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/start]}" onto public final boolean
 ink.abb.pogo.scraper.controllers.BotController.startBot(java.lang.String)
2016-08-08 17:21:44.887  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/load]}" onto public final void ink
.abb.pogo.scraper.controllers.BotController.loadBot(java.lang.String)
2016-08-08 17:21:44.887  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/unload]}" onto public final boolea
n ink.abb.pogo.scraper.controllers.BotController.unloadBot(java.lang.String)
2016-08-08 17:21:44.888  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/reload]}" onto public final boolea
n ink.abb.pogo.scraper.controllers.BotController.reloadBot(java.lang.String)
2016-08-08 17:21:44.888  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/stop]}" onto public final boolean
ink.abb.pogo.scraper.controllers.BotController.stopBot(java.lang.String)
2016-08-08 17:21:44.890  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.Res
ponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframewo
rk.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServ
letRequest)
2016-08-08 17:21:44.890  INFO 8652 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.spr
ingframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web
.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.serv
let.http.HttpServletResponse)
2016-08-08 17:21:44.908  INFO 8652 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class or
g.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:21:44.908  INFO 8652 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.spring
framework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:21:44.934  INFO 8652 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [clas
s org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:21:45.007  INFO 8652 --- [           main] o.s.j.e.a.AnnotationMBe
anExporter        : Registering beans for JMX exposure on startup
2016-08-08 17:21:45.040  INFO 8652 --- [           main] b.c.e.u.UndertowEmbedde
dServletContainer : Undertow started on port(s) 8080 (http)
2016-08-08 17:21:45.049  INFO 8652 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : Started MainKt in 2.053 seconds (JVM running for 2.378)
Exception in thread "1" com.fasterxml.jackson.core.JsonParseException: Unrecogni
zed token 'x': was expecting ('true', 'false' or 'null')
 at [Source: C:\Users\Danny\Desktop\New folder\.\bot-settings\1.json; line: 2, c
olumn: 16]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java
:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(Parser
MinimalBase.java:558)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidTo
ken(UTF8StreamJsonParser.java:3526)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpecte
dValue(UTF8StreamJsonParser.java:2683)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8St
reamJsonParser.java:832)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(Bea
nDeserializer.java:144)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMa
pper.java:3789)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.ja
va:2731)
        at ink.abb.pogo.scraper.services.BotService.load(BotService.kt:65)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$f
orEach$lambda$1.invoke(PokemonGoBotApplication.kt:62)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$$inlined$f
orEach$lambda$1.invoke(PokemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by CosmoRing** [comment] 2016-08-08 16:28
What do you have on the file 1.json in bot-settings folder?

**Comment by Sieberkev** [comment] 2016-08-08 16:28
Looks like you made an error in your 1.json config:

> Exception in thread "1" com.fasterxml.jackson.core.JsonParseException: Unrecogni
zed token 'x': was expecting ('true', 'false' or 'null')
at [Source: C:\Users\Danny\Desktop\New folder.\bot-settings\1.json; line: 2, c
olumn: 16]

**Comment by ItsFletch** [comment] 2016-08-08 16:46
Should i just get rid of the file in my bot-settings, I created it to see if that would fix it as the bot would not launch before that. Here is what i get if i try and launch without a file in there.


C:\Users\Danny\Desktop\New folder>start cmd /c cd desktop/new folder   && java -
jar PokemonGoBot-0.5.0.jar

2016-08-08 17:45:11.289  INFO 5868 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : Starting MainKt on Dannys-PC with PID 5868 (C:\Users\Danny\D
esktop\New folder\PokemonGoBot-0.5.0.jar started by Danny in C:\Users\Danny\Desk
top\New folder)
2016-08-08 17:45:11.292  INFO 5868 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : No active profile set, falling back to default profiles: def
ault
2016-08-08 17:45:11.340  INFO 5868 --- [           main] ationConfigEmbeddedWebA
pplicationContext : Refreshing org.springframework.boot.context.embedded.Annotat
ionConfigEmbeddedWebApplicationContext@506c589e: startup date [Mon Aug 08 17:45:
11 BST 2016]; root of context hierarchy
2016-08-08 17:45:12.304  INFO 5868 --- [           main] org.xnio
                  : XNIO version 3.3.6.Final
2016-08-08 17:45:12.344  INFO 5868 --- [           main] org.xnio.nio
                  : XNIO NIO Implementation Version 3.3.6.Final
2016-08-08 17:45:12.478  WARN 5868 --- [           main] io.undertow.websockets.
jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo
, the default worker will be used
2016-08-08 17:45:12.478  WARN 5868 --- [           main] io.undertow.websockets.
jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo
, the default pool will be used
2016-08-08 17:45:12.496  INFO 5868 --- [           main] io.undertow.servlet
                  : Initializing Spring embedded WebApplicationContext
2016-08-08 17:45:12.497  INFO 5868 --- [           main] o.s.web.context.Context
Loader            : Root WebApplicationContext: initialization completed in 1159
 ms
2016-08-08 17:45:12.679  INFO 5868 --- [           main] o.s.b.c.e.ServletRegist
rationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-08-08 17:45:12.685  INFO 5868 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-08-08 17:45:12.686  INFO 5868 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-08-08 17:45:12.686  INFO 5868 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-08-08 17:45:12.687  INFO 5868 --- [           main] o.s.b.c.embedded.Filter
RegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-08-08 17:45:12.952  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.cont
ext.embedded.AnnotationConfigEmbeddedWebApplicationContext@506c589e: startup dat
e [Mon Aug 08 17:45:11 BST 2016]; root of context hierarchy
2016-08-08 17:45:13.003  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/start]}" onto public final boolean
 ink.abb.pogo.scraper.controllers.BotController.startBot(java.lang.String)
2016-08-08 17:45:13.005  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bots]}" onto public final java.util.List<ink.
abb.pogo.scraper.Settings> ink.abb.pogo.scraper.controllers.BotController.bots()

2016-08-08 17:45:13.005  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/load]}" onto public final void ink
.abb.pogo.scraper.controllers.BotController.loadBot(java.lang.String)
2016-08-08 17:45:13.005  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/unload]}" onto public final boolea
n ink.abb.pogo.scraper.controllers.BotController.unloadBot(java.lang.String)
2016-08-08 17:45:13.006  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/reload]}" onto public final boolea
n ink.abb.pogo.scraper.controllers.BotController.reloadBot(java.lang.String)
2016-08-08 17:45:13.006  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/api/bot/{name}/stop]}" onto public final boolean
ink.abb.pogo.scraper.controllers.BotController.stopBot(java.lang.String)
2016-08-08 17:45:13.008  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.Res
ponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframewo
rk.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServ
letRequest)
2016-08-08 17:45:13.009  INFO 5868 --- [           main] s.w.s.m.m.a.RequestMapp
ingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.spr
ingframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web
.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.serv
let.http.HttpServletResponse)
2016-08-08 17:45:13.028  INFO 5868 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class or
g.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:45:13.029  INFO 5868 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.spring
framework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:45:13.062  INFO 5868 --- [           main] o.s.w.s.handler.SimpleU
rlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [clas
s org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-08-08 17:45:13.145  INFO 5868 --- [           main] o.s.j.e.a.AnnotationMBe
anExporter        : Registering beans for JMX exposure on startup
2016-08-08 17:45:13.181  INFO 5868 --- [           main] b.c.e.u.UndertowEmbedde
dServletContainer : Undertow started on port(s) 8080 (http)
2016-08-08 17:45:13.185  INFO 5868 --- [           main] ink.abb.pogo.scraper.Ma
inKt              : Started MainKt in 2.133 seconds (JVM running for 2.474)
08 Aug 17:45:13 (default): Logging in to game server...
08 Aug 17:45:14 (default): Logged in successfully
Getting profile data from pogo server.
D/RequestHandler: Authenticated with static token
08 Aug 17:45:15 (default):
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException:
Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.j
ava:155)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.ja
va:77)
        at com.pokegoapi.api.player.PlayerProfile.getPlayerData(PlayerProfile.ja
va:227)
        at ink.abb.pogo.scraper.Bot.start(Bot.kt:60)
        at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:144)
        at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:57)
        at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(P
okemonGoBotApplication.kt:46)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException:
com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidP
rotocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFutur
e.call(OnSubscribeToObservableFuture.java:43)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.j
ava:445)
        ... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffe
r are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
        at java.lang.Thread.run(Unknown Source)

**Comment by CosmoRing** [comment] 2016-08-08 16:50
There seems to be 2 other issues with the same problem: #852 #850

For now seems there isn't any solution.

**Comment by ItsFletch** [comment] 2016-08-08 16:53
Dam, Does anyone know of a simple Transfer and item bin bot i can use in the mean time....
If not a bin bot one that will just transfer. I need something that will transfer pokemon under a set CP and keep at least 1 of each pokemon regardless of CP.

**Comment by langerhans** [comment] 2016-08-11 18:35
Closing as duplicate of #850.

**Closed by langerhans** 2016-08-11 18:35 UTC
