### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by Padrino02** [jabbink/PokemonGoBot#634] opened 2016-07-29 13:25 UTC
```
29 Jul 15:19:27: Getting map of (40.75885364914553, 73.9872863070797)
29 Jul 15:19:27: Getting initial pokestops...
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are
null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at ink.abb.pogo.scraper.Bot.start(Bot.kt:92)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:134)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 5 more
```

Whats wrong?

Oh and also what do I have to put in at "token"?

Thanks

**Comment by Sieberkev** [comment] 2016-07-29 13:26
Exception => Duplicate of #627

Token should be empty, will be filled in by the bot after Google Auth :smile:

**Comment by SiriusCrypto** [comment] 2016-07-29 13:28
Please search first, many issues like this already open. Please Close your issue.
 #608

**Comment by Padrino02** [comment] 2016-07-29 13:29
Ohh I'm sorry I didn't saw that.
Any solutions so far?

Allright, thank you

**Closed** 2016-07-29 13:29 UTC
