### ISSUE TITLE
Code doesnt catch all pokemons found in area

### ISSUE THREAD

**Issue by surfaace** [jabbink/PokemonGoBot#44] opened 2016-07-22 05:55 UTC
I've added some more output and found that you are not looping through an catching all pokemons in the area before moving on:

Pokemons in area: 4
found pokemon MAGIKARP
encountered pokemon MAGIKARP
Caught a MAGIKARP using a ITEM_POKE_BALL
Found nearby pokestop
Activated portal 040f1eda22774a05b131d631ab2092be.16
Getting map of 59.32902522445945 18.063510787215506
Pokemons in area: 2
found pokemon KAKUNA
encountered pokemon KAKUNA
Caught a KAKUNA using a ITEM_POKE_BALL
Profile update : 88670 XP on LVL 14; 13670/25000 (54,68%) to LVL 15
destination reached
Getting map of 59.32905008084083 18.063505562625785
Pokemons in area: 0
Profile update : 88670 XP on LVL 14; 13670/25000 (54,68%) to LVL 15

And in the code its reflected with:

            val catchablePokemon = pokemon.first()
            println("found pokemon ${catchablePokemon.pokemonId}")

I've tried to do a for loop but for some reason it doesnt like my code style so it wont build.

**Comment by jabbink** [comment] 2016-07-22 08:27
Duplicate of #21

**Closed by jabbink** 2016-07-22 08:27 UTC
