### ISSUE TITLE
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 

### ISSUE THREAD

**Issue by newguy05** [jabbink/PokemonGoBot#729] opened 2016-08-01 14:36 UTC
Hi, have this really annoying error below. It happens randomly after I leave it on for a while - pretty much every time i turn it on then come back to it later it stopped working and is spamming this error. I checked the pokemon server by login in with the app itself and everything was fine. 

Not sure how to debug this since the stack trace isn't saying anything. 

I am using the latest prebuilt jar  pogo.scraper-all-0.5.0-alpha4.jar  and java 1.8 

My config looks like below:

username=xxxxx@gmail.com
password=xxxxxx
base64_password=
#token=
latitude=xxxxxx
longitude=-xxxxxx
etc...

ERROR:

01 Aug 10:13:36: Getting map of (xxxxx, xxxxx)
D/RequestHandler: Authenticated with static token
01 Aug 10:13:37: Error running loop BotLoop! 
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)
01 Aug 10:13:41: Getting map of (xxxxx, xxxxx)
D/RequestHandler: Authenticated with static token
01 Aug 10:13:42: Error running loop BotLoop! 
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)
01 Aug 10:13:46: Getting map of (xxxxx, xxxxx)
D/RequestHandler: Authenticated with static token
01 Aug 10:13:47: Error running loop BotLoop! 
com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
	at java.lang.Thread.run(Thread.java:745)
01 Aug 10:13:51: Getting map of (xxxxx, xxxxx)
D/RequestHandler: Authenticated with static token

**Comment by Sieberkev** [comment] 2016-08-01 14:37
Duplicate of #716

**Comment by vamirineni87** [comment] 2016-08-01 14:37
duplicate of #720

**Closed** 2016-08-01 20:18 UTC
Labels: duplicate, Search before posting
