### ISSUE TITLE
Unknown Exception Error

### ISSUE THREAD

**Issue by fm360** [jabbink/PokemonGoBot#869] opened 2016-08-08 21:43 UTC
**Description:**
Bot goes through regular startup but once startup finishes, I get an unknown exception

**Steps to reproduce:**

1. Type "java -jar PokemonGoBot-0.5.0.jar"

**Expected behavior:**
The bot should start up like normal and do its regular thing

**Actual behavior:**
Unknown java exception occurs

**Stacktrace (If it's a crash):**
Exception in thread "default" com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
	at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
	at com.pokegoapi.api.player.PlayerProfile.getStats(PlayerProfile.java:304)
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)

**Version:**
0.5.0 final build

**Operating System:**
Mac OSX 10.11.4

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by fm360** [comment] 2016-08-08 21:46
Oh I just found a fix just type "java -jar PokemonGoBot-0.5.0.jar --server.port=8090" instead. Please close this issue.

**Comment by blindxscript** [comment] 2016-08-08 21:48
its working with this fix. thanks a lot! 👍

**Comment by Rofii** [comment] 2016-08-08 21:50
@fm360 The person who opened the issue is also able to close it. That's you. :+1:

**Comment by Mahdude** [comment] 2016-08-08 22:42
Where do you enter "java -jar PokemonGoBot-0.5.0.jar --server.port=8090" ?

**Comment by brewskis** [comment] 2016-08-09 01:53
java -jar PokemonGoBot-0.5.0.jar --server.port=8090

This no longer works. Does anyone know why this issue is occurring? What can I do to fix this?

**Comment by NinjaStew** [comment] 2016-08-09 02:01
You're not properly closing the program and it's leaving the ports open. Restart your computer and it will fix the program. Next time you go to exit or restart the jar, use ctrl+c to kill the program then type "exit" into your console.

**Comment by langerhans** [comment] 2016-08-11 18:52
Duplicate of #850

**Closed by langerhans** 2016-08-11 18:52 UTC
