### ISSUE TITLE
[Suggestion] Save last location

### ISSUE THREAD

**Issue by victorespada** [jabbink/PokemonGoBot#397] opened 2016-07-26 11:01 UTC
I think that should be a great idea save last location in config.properties, then when we start the plugin we will start in the last location... because now, if I have the bot 30 minutes walking and I start again there will be much difference in distance.

**Comment by jabbink** [comment] 2016-07-26 11:48
Duplicate of #144

**Closed by jabbink** 2016-07-26 11:48 UTC
