### ISSUE TITLE
[Suggestion] Runtime to calculate XP/HR

### ISSUE THREAD

**Issue by mroge009** [jabbink/PokemonGoBot#411] opened 2016-07-26 14:16 UTC
Add runtime to the the update profile to display XP/HR since that is how many in the botting community seem to compare bots.  
Ive gotten around 40k/hr with this one.

**Comment by shilch** [comment] 2016-07-26 15:05
I think it depends on the location and time how much xp you get per hour.

**Comment by mroge009** [comment] 2016-07-26 15:42
@shilch Yes. But this way you can test out which location works best for you.

**Comment by MASSV** [comment] 2016-07-26 16:39
Location is a huge factor. Bot on santa monica beach/pier gets +-50% over new york central park, double that of small town bot.

**Comment by jabbink** [comment] 2016-07-26 22:26
Duplicate of #376

**Closed by jabbink** 2016-07-26 22:26 UTC
