### ISSUE TITLE
Error running loop BotLoop! 

### ISSUE THREAD

**Issue by CptJackieSparrow** [jabbink/PokemonGoBot#630] opened 2016-07-29 10:58 UTC
29 Jul 13:56:40: Error running loop BotLoop! 
com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:103)
	at ink.abb.pogo.scraper.tasks.WalkToUnusedPokestop.run(WalkToUnusedPokestop.kt:24)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:44)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:163)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:115)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:30)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:128)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:30)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
	at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
	... 13 more

version v0.4.3

**Comment by Sieberkev** [comment] 2016-07-29 11:02
Duplicate of #627

**Closed** 2016-07-29 11:10 UTC
