### ISSUE TITLE
[Suggestion] Using CP% instead of CP value for transfers

### ISSUE THREAD

**Issue by omar972** [jabbink/PokemonGoBot#314] opened 2016-07-25 13:33 UTC
So, currently, the way transferring works is you choose the CP threshold and any Pokemon that is below that threshold might be tranferred. My problem with this is that isn't very reliable for keeping the better Pokemon. For example an 600 CP Eeeve is great, and will be more than 1800 cp if evolved into Vaporeon, a 600 CP Vaporeon isn't as great.

In case you're not aware, the CP level of a Pokemon depends on it's IVs, % power level (each pokemon has a sort of semi-circle under it's CP, the more full it is, the higher the %), and it's evolutionary state. So transferring based on % power level would be much more reliable.

**Comment by dyoung81** [comment] 2016-07-25 13:36
just use -1 for CP and add the percent you want to keep in min IV, this is already an option

**Comment by CptJackieSparrow** [comment] 2016-07-25 13:48
IV is not CP, actually i couldn't find any information about IV, can someone explain?
Should i keep 26 CP %100 IV
or
Should i keep 1600 CP &20 IV
What does it actually means?

**Comment by omar972** [comment] 2016-07-25 13:59
IVs are values that cannot be changed once you have caught the pokemon and add to the max CP a pokemon can have. So you can have anything between 1 and 15 IV for strength, defense and stamina. If you have 15 strength, defense and stamina, then you have 100% IVs which is extremely rare and desirable, if you have  14 strength, 12 defense and 10 stamina then you have 80% IVs which is the default threshold in the config, anything that has less than that may be transferred if none of the other config options decide to keep it. CP is simply combat power.

**Comment by pvase666** [comment] 2016-07-25 16:54
Bot keep pokemons that >80% IV but too small CP. :(

**Comment by omar972** [comment] 2016-07-25 17:00
# Sort by IV first instead of CP
sort_by_iv=true

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

**This will keep all pokemon that are >= 80% IVs and >= 400 CP**

**Comment by pvase666** [comment] 2016-07-25 17:09
@omar972 I will test :dancer:

**Comment by jabbink** [comment] 2016-07-25 18:41
Removed unrelated comments.

**Comment by omar972** [comment] 2016-07-25 22:02
@jabbink Are you going to consider this or?

**Comment by Spyderdreams** [comment] 2016-07-26 08:17
IV is a better gauge of potential. Max CP always changes because it isn't only based on Pokemon. The trainer lvl and IV determine your current max CP.

Have you noticed that a maxed CP Pokemon is not maxed after you lvl?

**Comment by jabbink** [comment] 2016-07-26 08:40
@omar972 I'm kind of hesitant as the general consesus is that a 100% IV pokemon with 10 CP is still better than the same pokemon with 0% IV and 400 CP, as you can cheaply evolve/power up that 100% IV pokemon and get a >>400 CP pokemon out of it that will be stronger in the long run.

Also at this moment there is no way for me to calculate the max cp, and therefore the percentage, I think.

**Comment by pdgwien** [comment] 2016-07-26 09:08
@jabbink: If you are looking for the formula to calculate a pokemons max CP, look [https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/](here). Most of the needed values you already have, so you would just need to plug them in there.

**Comment by jabbink** [comment] 2016-08-15 20:50
Duplicate of #159 and sort of implemented.

**Closed by jabbink** 2016-08-15 20:50 UTC
