### ISSUE TITLE
[Enhancement request] remember last GPS location

### ISSUE THREAD

**Issue by vamirineni87** [jabbink/PokemonGoBot#755] opened 2016-08-02 18:04 UTC
**Description:**
[I recall seeing this before as a request, but cant find in search. Similar to the token is it possible to include remembering last GPS location when the bot was closed? both gracefully or forcefully. This might require a periodic update of coordinates. This should go hand in hand with the allow_leave_start_area setting. ]

**Comment by Cypherke** [comment] 2016-08-02 18:05
Duplicate of #144

**Closed** 2016-08-02 18:06 UTC
