### ISSUE TITLE
HELP! Error runing loop BotLoop

### ISSUE THREAD

**Issue by lBeher** [jabbink/PokemonGoBot#857] opened 2016-08-08 18:29 UTC
I have a problem. When the bot has been runing for 20-30 min always crash with this error:

08 ago 20:27:00 (default: BotLoop): Getting map of (37.8087843064814, -122.40967000168312)
08 ago 20:27:01 (default: BotLoop): **Error running loop BotLoop!** 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.

Any idea to solve it?

**Comment by Sieberkev** [comment] 2016-08-08 18:45
Can you show us the full stack trace?

Also can you please fill in the whole issue template? (JAR version, GIT/build commit, java version, ...) sinces we're missing a whole lot of usefull information like this :/

**Comment by tzutzanu** [comment] 2016-08-08 19:03
I get the same after running for a while (1hr or so). I don't think it's related to the full inventory as it works for quite a bit with full inventory (or rather I'm almost always full).

`08 Aug 02:02:53 (default: BotLoop): Getting map of (52.53625243553051, 13.428514860238858)
08 Aug 02:02:54 (default: BotLoop): Looting nearby pokestop "Happy Friends Mural"
08 Aug 02:02:55 (default: BotLoop): Looted pokestop "Happy Friends Mural"; +50 XP, but inventory is full: [] 
08 Aug 02:02:58 (default: BotLoop): Getting map of (52.53613854117559, 13.428543824399792)
08 Aug 02:03:03 (default: BotLoop): Getting map of (52.536047085529226, 13.428575714235766)
08 Aug 02:03:05 (default: WalkingLoop): Destination reached.
08 Aug 02:03:08 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:158)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
08 Aug 02:03:08 (default: BotLoop): Getting map of (52.53596927113789, 13.4285864606067)
08 Aug 02:03:11 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.fort.Pokestop.getDetails(Pokestop.java:231)
	at ink.abb.pogo.scraper.gui.SocketServer.sendPokestop(SocketServer.kt:104)
	at ink.abb.pogo.scraper.tasks.Walk.run(Walk.kt:55)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.tasks.ProcessPokestops.run(ProcessPokestops.kt:54)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:131)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 13 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
08 Aug 02:03:13 (default: BotLoop): Getting map of (52.5359438624968, 13.428603778473024)
08 Aug 02:03:13 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:158)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.RemoteServerException: Got a unexpected http code : 502
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:197)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
08 Aug 02:03:18 (default: BotLoop): Getting map of (52.535970410201635, 13.428571392539475)
08 Aug 02:03:23 (default: BotLoop): Getting map of (52.535982021538345, 13.428601086462098)
08 Aug 02:03:39 (default: ProfileLoop): Failed to update profile and inventories 
08 Aug 02:03:42 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:158)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
08 Aug 02:03:42 (default: ProfileLoop): Error running loop ProfileLoop! 
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)
08 Aug 02:03:42 (default: BotLoop): Getting map of (52.53602615790044, 13.428590164550057)
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
	at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:66)
	at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:116)
	at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)
08 Aug 02:03:43 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:158)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
	at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:293)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by lBeher** [comment] 2016-08-08 20:09
Here is..

08 ago 21:59:53 (default: BotLoop): Error running loop BotLoop! 
com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
	at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:158)
	at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
	at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:28)
	at ink.abb.pogo.scraper.Bot.task(Bot.kt:221)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:124)
	at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:33)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:169)
	at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:33)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
	at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:9861)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:9957)
	at rx.Observable.subscribe(Observable.java:9924)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
	... 11 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
	at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
	at java.lang.Thread.run(Thread.java:745)
D/RequestHandler: Authenticated with static token

**Comment by tzutzanu** [comment] 2016-08-08 20:28
Yes, my bot gives Beher's stack above too, but the first few instances of the error are the ones I pasted. After a while it stops complaining about those and starts complaining about the token refresh.

**Comment by michaeldajnowicz** [comment] 2016-08-08 23:27
its just the token refresh

**Comment by tzutzanu** [comment] 2016-08-09 06:29
@michaeldajnowicz "it's just the token refresh" means exactly nothing. It is an error that is not handled properly in the code which causes the bot to be unusable after 1-2hrs when it happens to first run into it, since it never recovers even though the error that causes it is transient. The bot should have proper error-handling for this case - a 502 HTTP response usually means an overloaded server, pretty common nginx error to see, etc. So it should be identified as a likely overwhelmed server and retry after some reasonable interval like 30s or a minute.

**Comment by jabbink** [comment] 2016-08-09 15:39
try 0.5.1

for the RemoteServerExceptions/null from server/502: Pogo server is temporarily broken. Just wait.

**Comment by langerhans** [comment] 2016-08-11 18:37
See comment above, all those issues exist in the repo already, therefore closing.

**Closed by langerhans** 2016-08-11 18:37 UTC
