### ISSUE TITLE
Bot only catching a few Pokémon

### ISSUE THREAD

**Issue by kasagon** [jabbink/PokemonGoBot#672] opened 2016-07-31 00:24 UTC
**Description:**
I got the bot running for a little bit more then a hour now, and it seems that the bot is ignoring the most of the Pokémon.

In the past hour the bot has caught 5 Pokémon, while the map (live map) is showing a lot more then that. I don't know if it is my settings or something else.

My settings:
http://pastebin.com/83Tyw4qC

**Steps to reproduce:**

1. Run the bot

**Expected behavior:**
Catch more Pokémon instead of ignoring the most of them

**Actual behavior:**
Catches 5 Pokemon in a hour, ignores the most Pokemon

**Version:**
Commit  62e2fb1 
I edited 2 files, but those are files from the web GUI ( #671 )

**Operating System:**
Windows 10 PRO 64-bit

**Java version:**

    C:\>java -version
    java version "1.8.0_102"
    Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Natedog2012** [comment] 2016-07-31 00:43
Having the same issue with the alpha3.. caught 0 / 0 .. it skips almost every pokemon it comes near

**Comment by SiriusCrypto** [comment] 2016-07-31 00:51
I dont see that it enounters any pokemon all i see is it keeps saying pausing to catch pokemon over and over without any result or anything else:

> 31 Jul 02:49:33: Pausing to catch pokemon...
31 Jul 02:49:33: Dropped 3x ITEM_POKE_BALL 
31 Jul 02:49:35: Dropped 1x ITEM_GREAT_BALL 
31 Jul 02:49:36: Dropped 2x ITEM_RAZZ_BERRY 
31 Jul 02:49:40: Pausing to catch pokemon...
31 Jul 02:49:46: Pausing to catch pokemon...
31 Jul 02:49:51: Pausing to catch pokemon...
31 Jul 02:49:56: Pausing to catch pokemon...
31 Jul 02:49:58: Destination reached.
31 Jul 02:50:00: Walking to (52.37023, 4.900303) in 100.36417700579715 steps.
31 Jul 02:50:05: Pausing to catch pokemon...
31 Jul 02:50:10: Pausing to catch pokemon...
31 Jul 02:50:16: Pausing to catch pokemon...
31 Jul 02:50:21: Pausing to catch pokemon...
31 Jul 02:50:25: Pausing to catch pokemon...

**Comment by kasagon** [comment] 2016-07-31 00:52
@Natedog2012 I am running Alpha3 as well, but with a few commits (3 or 4 I think)

It is running for 90 minutes now, 30 minutes after I made this post, and it still has caught 5 Pokemon

**Comment by Natedog2012** [comment] 2016-07-31 01:16
Getting an error sometimes when it tries to catch pokemon as well...

30 Jul 18:10:38: Found pokemon DIGLETT
30 Jul 18:10:38: Encountered pokemon DIGLETT with CP 169 and IV 40%
30 Jul 18:10:38: Using desired_catch_probability_unwanted because CP < 500 and IV < 85%
30 Jul 18:10:38: Using ITEM_POKE_BALL; achieved catch probability: 0.35288644, desired: 0.0
30 Jul 18:10:39: Error running loop BotLoop!
java.lang.NullPointerException
        at com.pokegoapi.api.map.pokemon.CatchResult.getStatus(CatchResult.java:45)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:45)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:62)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:123)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
30 Jul 18:10:42: Getting map of (34.00972013343425, -118.49332248234569)
30 Jul 18:10:43: Found pokemon DIGLETT
30 Jul 18:10:43: Encountered pokemon DIGLETT with CP 169 and IV 40%

**Comment by SiriusCrypto** [comment] 2016-07-31 01:39
Servers are having issues atm, could just be that? Or might have something to do with  [This](https://github.com/jabbink/PokemonGoBot/commit/a67bdfb123bb8f0d4382b4da2a1a4cffcde7afdb) commit by  @pashorizer

**Comment by celsian** [comment] 2016-07-31 01:54
The scan speed has been changed by the API. It will only respond to one scan every five seconds. Drop your walking speed and see if it improves.

**Comment by HoneyWheat** [comment] 2016-07-31 06:48
Imho an important issue because stardust is the limiting ressource, you can't have enough of ot.

**Comment by GeitV** [comment] 2016-07-31 06:58
Yeah having the exact same log as Sirius, as of I get alot of "Pausing to catch pokemon..." but it doesn't pause it seems. I still have caught some pokemons but it seems sometimes the pausing doesn't work and it cannot catch the pokemon.

**Comment by casper-gh** [comment] 2016-07-31 07:04
I'm getting very little to no pokemon at all, tested with walk speed from 1 to 30 but still the same

**Comment by HoneyWheat** [comment] 2016-07-31 07:14
Snapshot: Bot is running for 30min in a city area full of Pokestops. Got only 400 startdust in 30min.

**Comment by pashorizer** [comment] 2016-07-31 08:29
There is a new throttle from Niantic regarding the server response.

**Comment by GeitV** [comment] 2016-07-31 09:07
I did my own fix for this, seems to work atm (not a good solution as it stops the program, but well works at the moment) I do not wanna push, as I hope someone gets better function, its just temporary. If anyone wants to fix this, check the image and you will understand what to do

https://gyazo.com/009994399be08acb56f65447e069ae6c

For me it seems to be able to catch again, but don't take this granted

**Comment by casper-gh** [comment] 2016-07-31 09:09
actually increasing the move speed to 25+ will help catch more pokemon, not sure if i'll get banned

**Comment by GeitV** [comment] 2016-07-31 09:20
25 m/s, that is 90km/h and you are able to catch? Whoa, I thought the limit was 20-25 km/h

**Comment by pashorizer** [comment] 2016-07-31 09:25
Right now, even if you set the speed to 1000. It will not go that fast, because some API calls take a long time to answer so the bot blocks himself. This is going to be fixed with this https://github.com/jabbink/PokemonGoBot/pull/664 
Then you can set a speed e.g. 5, 10, 15, 20 and it will go that fast and stop every 20 steps to check for pokemon around him.
As a side note, I also tried to go with 25m/s on a throwaway account and it did not get banned. But highly risky. Choose on your own.

**Comment by GeitV** [comment] 2016-07-31 09:36
Ok, thanks for heads-up :) Will try with higher speeds also

**Comment by kasagon** [comment] 2016-07-31 11:08
Bot has been running for 11 hours.
Caught 5 Pokemon in total, and got so many botloop and walkingloop errors that it only traveled ~1.7km in the last 9 hours.

**Comment by qifbox** [comment] 2016-07-31 11:39
I changed settings to 1.5 m/s and started having more pokemons. 
But looping errors too..

Error
--
31 jul 12:35:23: Found pokemon PIDGEY
31 jul 12:35:23: Encountered pokemon PIDGEY with CP 217 and IV 28%
31 jul 12:35:23: Using desired_catch_probability_unwanted because CP < -1 and IV < 80%
31 jul 12:35:23: Using ITEM_POKE_BALL; achieved catch probability: 0.40011334, desired: 0.0
31 jul 12:35:24: Error running loop BotLoop!
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null
        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.map.pokemon.CatchablePokemon$3.handle(CatchablePokemon.java:408)
        at com.pokegoapi.api.map.pokemon.CatchablePokemon$3.handle(CatchablePokemon.java:396)
        at com.pokegoapi.util.FutureWrapper.getResult(FutureWrapper.java:78)
        at com.pokegoapi.util.FutureWrapper.get(FutureWrapper.java:53)
        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:108)
        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:94)
        at com.pokegoapi.api.map.pokemon.CatchablePokemon.catchPokemon(CatchablePokemon.java:347)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:27)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:115)
        at ink.abb.pogo.scraper.util.pokemon.CatchablePokemonKt.catch(CatchablePokemon.kt:42)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:62)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:123)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
31 jul 12:35:27: Getting map of (38.70588197434313, -9.143618616274567)
31 jul 12:35:32: Getting map of (38.70585971939362, -9.14356553821557)
31 jul 12:35:37: Getting map of (38.70585992724561, -9.143601047507861)
31 jul 12:35:38: Profile update: 294075 XP on LVL 21; 34075/75000 (45,43%) to LVL 22
31 jul 12:35:38: XP gain: 1400 XP; Pokemon caught/transferred: 2/1; Items caught/dropped: 0/2;
Pokebank 87/250; Stardust 3266; Inventory 267/350
com.pokegoapi.exceptions.RemoteServerException: Contents of buffer are null31 jul 12:35:39: Error running loop ProfileLoop!

        at com.pokegoapi.util.FutureWrapper.toBlocking(FutureWrapper.java:119)
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:154)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:108)
        at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
        at com.pokegoapi.api.inventory.Hatchery.queryHatchedEggs(Hatchery.java:75)
        at ink.abb.pogo.scraper.tasks.HatchEggs.run(HatchEggs.kt:22)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:201)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:115)
        at ink.abb.pogo.scraper.Bot$start$3.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:78)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:292)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
31 jul 12:35:42: Getting map of (38.70591455035207, -9.143588184881898)
31 jul 12:35:43: Going to transfer PIDGEY with CP 217 and IV 28%; reason: CP < -1 and IV < 80%

**Comment by kasagon** [comment] 2016-07-31 12:00
@pashorizer With #664 the bot ignored the first few encounters, but after that it encountered Pokémon again. But, the bot encounters those Pokémon really late, it has caught 5 Pokémon now, but haven't encountered one for a few minutes, but the bot is walking right now on a place where less to none Pokémon are, so that can be right.

I set a path for the bot that comes across some places with a lot of Pokémon (2+ in a range of 15 metres), but that path will take a while. So I am curious it will catch more Pokémon now.

**Comment by TheJ0k3r** [comment] 2016-07-31 13:44
maybe its because the cordinates you use man mine catches 17 pokemon in an half hour maybe new cordinates?

**Comment by d0tamon** [comment] 2016-07-31 16:13
Mine has a similar situation as well. and random BotLoops along the way

**Comment by yashendra2797** [comment] 2016-07-31 16:25
Yup. Same here. *way* less pokemons caught in same area as yesterday when I used Alpha 2

**Comment by kasagon** [comment] 2016-07-31 18:50
@TheJ0k3r I was at the location there earlyer today, and there are a lot of Pokemon.
I used @pashorizer fix, and it catches a lot more Pokemon.

**Comment by vaneske** [comment] 2016-07-31 19:33
Confirmed.  @pashorizer fix works.

**Comment by langerhans** [comment] 2016-07-31 20:05
Closing as the latest release should fix this.

**Comment by casper-gh** [comment] 2016-07-31 20:05
@vaneske what walk speed are you using?

**Closed by langerhans** 2016-07-31 20:05 UTC

**Comment by vaneske** [comment] 2016-07-31 20:07
@casper-gh default speed of 2.8
