### ISSUE TITLE
0 initial pokestops found. retrying in 10 seconds.

### ISSUE THREAD

**Issue by alkalisdad** [jabbink/PokemonGoBot#704] opened 2016-07-31 21:28 UTC
**Description:**
0 initial pokestops found. retrying in 10 seconds.

**Steps to reproduce:**

**Expected behavior:**
Bot starts

**Actual behavior:**
Error message comes up 

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
5.0.4

**Operating System:**
[Your operating system]

**Java version:**
[Full output of `java -version`]

**Comment by Sieberkev** [comment] 2016-07-31 21:29
Duplicate of #686

**Comment by langerhans** [comment] 2016-08-01 06:32
Check your lat/lon. You probably mixed something up there.

**Closed by langerhans** 2016-08-01 06:32 UTC
