### ISSUE TITLE
Unexpected error is displayed when running the bot

### ISSUE THREAD

**Issue by breinntaguilar** [jabbink/PokemonGoBot#1017] opened 2016-08-12 06:51 UTC
**Description:**
Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake

**Steps to reproduce:**

1. Run the bot using --> java -jar xxxx.jar
2. Wait for the console to display the error message.

**Expected behavior:**
Everything should run smoothly.

**Actual behavior:**
Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake is returned.

**Stacktrace (If it's a crash):**
[Please use pastebin if it's too long]

**Version:**
v 0.5.2

**Operating System:**
OSX El Capitan

**Java version:**
breinn@lemonade:~/Desktop/PoGoBot$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Peyphour** [comment] 2016-08-12 07:05
Wow that's new

**Comment by breinntaguilar** [comment] 2016-08-12 07:07
![screen shot 2016-08-12 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/2063011/17615110/657498d8-609e-11e6-80c4-744d6e4329a6.png)

**Comment by Peyphour** [comment] 2016-08-12 07:07
Does it do this each you launch the bot ?

**Comment by breinntaguilar** [comment] 2016-08-12 07:07
@Peyphour yes. its the same. tried to run it 5 times already before i stopped.

**Comment by breinntaguilar** [comment] 2016-08-12 07:10
Checked the logfile and i got this.

12 Aug 15:08:17 [main] - Running with Spring Boot v1.3.6.RELEASE, Spring v4.2.7.RELEASE
12 Aug 15:08:17 [main] - No active profile set, falling back to default profiles: default
12 Aug 15:08:21 [main] - UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
12 Aug 15:08:21 [main] - UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
12 Aug 15:08:24 [main] - Started MainKt in 7.986 seconds (JVM running for 11.313)
12 Aug 15:08:24 [default] - Trying to read /Users/breinn/Desktop/PoGoBot/PokemonGoBot/config.properties
12 Aug 15:08:25 [default] - Logging in to game server...
12 Aug 15:08:45 [default] - Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
12 Aug 15:08:45 [default] - Retrying...
12 Aug 15:09:07 [default] - Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
12 Aug 15:09:07 [default] - Retrying...
12 Aug 15:09:28 [default] - Server returned unexpected error: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
12 Aug 15:09:28 [default] - Retrying...

**Comment by Peyphour** [comment] 2016-08-12 07:11
Which auth are you using ?

**Comment by Peyphour** [comment] 2016-08-12 07:12
Just checked server status, PTC and Google login are down at the moment

**Comment by breinntaguilar** [comment] 2016-08-12 07:13
I used Google as my auth for bot. Thanks for confirming bro. I will send an update maybe later once they are up. By the way, how do you check their status? So I would know when to start trying again the bot. 

Thanks!

**Comment by Peyphour** [comment] 2016-08-12 07:15
ispokemongodownornot.com

**Comment by breinntaguilar** [comment] 2016-08-12 07:17
Thanks bro!

**Comment by Mixone-FinallyHere** [comment] 2016-08-12 08:03
error checking is so much simpler when from source hahaha

reading in stackoverflow he might be missing the security certificates in his java causing the remote to close the connection since it did not get any certificates

thats is only one of many possibilities though

**Comment by Sieberkev** [comment] 2016-08-24 21:05
Server problem, will close this issue to clean up the issue tracker. Feel free to reply if the problem is still not solved!

**Closed by Sieberkev** 2016-08-24 21:05 UTC
