### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by pikachukaki** [jabbink/PokemonGoBot#542] opened 2016-07-28 01:15 UTC
I just d/w this file and i can't or it wont let me login my credentials are correct!!
Server refused your login credentials. Are they correct?

**Comment by Agronis** [comment] 2016-07-28 01:16
Please, form a complete sentence - even if in another language.

I don't understand what the problem is beyond possibly the fact the program is telling you that your credentials you entered are incorrect.

**Comment by pikachukaki** [comment] 2016-07-28 01:16
Ok my bad it didn't want the google maps token in the config file!!!

**Comment by Agronis** [comment] 2016-07-28 01:16
Please close this issue.

**Comment by pikachukaki** [comment] 2016-07-28 01:16
calm m8

**Comment by Agronis** [comment] 2016-07-28 01:17
Welcome to github.

**Closed** 2016-07-28 01:17 UTC
