### ISSUE TITLE
Stack doing nothing, just getting map area

### ISSUE THREAD

**Issue by staurakis** [jabbink/PokemonGoBot#978] opened 2016-08-11 06:18 UTC
Since yesterday, i am experiencing the following out of sudden: 

Pokebank 161/350; Stardust 634222; Inventory 850/850
←[0;39m←[37m11 ┴Ϋή 09:12:20 [default: ProfileLoop] - Wrote export.
←[0;39m←[37m11 ┴Ϋή 09:12:22 [default: BotLoop] - Getting map of (37.973944406015356, 23.73562013970657)
←[0;39m←[37m11 ┴Ϋή 09:12:27 [default: BotLoop] - Getting map of (37.973976672146385, 23.735600330120395)
←[0;39m←[37m11 ┴Ϋή 09:12:32 [default: BotLoop] - Getting map of (37.973926505237785, 23.73554642013613)
←[0;39m←[37m11 ┴Ϋή 09:12:37 [default: BotLoop] - Getting map of (37.97391699592654, 23.73560409087552)
←[0;39m←[37m11 ┴Ϋή 09:12:42 [default: BotLoop] - Getting map of (37.97392817159642, 23.73561974946312)
←[0;39m←[37m11 ┴Ϋή 09:12:47 [default: BotLoop] - Getting map of (37.97391953450034, 23.735573953836354)
←[0;39m←[37m11 ┴Ϋή 09:12:52 [default: BotLoop] - Getting map of (37.97398742317468, 23.7355783068823)
←[0;39m←[37m11 ┴Ϋή 09:12:57 [default: BotLoop] - Getting map of (37.97400257148638, 23.735608387914503)
←[0;39m←[37m11 ┴Ϋή 09:13:02 [default: BotLoop] - Getting map of (37.97397148828697, 23.735578001586493)
←[0;39m←[37m11 ┴Ϋή 09:13:07 [default: BotLoop] - Getting map of (37.973943222960024, 23.735576189937685)
←[0;39m←[37m11 ┴Ϋή 09:13:12 [default: BotLoop] - Getting map of (37.97396425315168, 23.735609263583616)
←[0;39m←[37m11 ┴Ϋή 09:13:17 [default: BotLoop] - Getting map of (37.97394372847153, 23.735550817012367)
←[0;39m←[35m11 ┴Ϋή 09:13:20 [default: ProfileLoop] - Profile update: 1871990 XP on LVL 29; 221990/350000 (63,43%) to LVL 30
←[0;39m←[35m11 ┴Ϋή 09:13:20 [default: ProfileLoop] - XP gain: 950 XP in 18 mins; XP rate: 3.120/hr
Pokemon caught/transferred: 2/2; Pokemon caught from lures: 0; Items caught/dropped: 12/5;
Pokebank 161/350; Stardust 634222; Inventory 850/850
←[0;39m←[37m11 ┴Ϋή 09:13:21 [default: ProfileLoop] - Wrote export.
←[0;39m←[37m11 ┴Ϋή 09:13:22 [default: BotLoop] - Getting map of (37.97398078790052, 23.735577617113975)
←[0;39m←[37m11 ┴Ϋή 09:13:27 [default: BotLoop] - Getting map of (37.97397836198885, 23.735596772071762)
←[0;39m←[37m11 ┴Ϋή 09:13:32 [default: BotLoop] - Getting map of (37.97400355847891, 23.73557714129033)
←[0;39m←[37m11 ┴Ϋή 09:13:37 [default: BotLoop] - Getting map of (37.97398475972679, 23.735627039773675)
←[0;39m←[37m11 ┴Ϋή 09:13:42 [default: BotLoop] - Getting map of (37.97396784213199, 23.735591488939622)
←[0;39m←[37m11 ┴Ϋή 09:13:47 [default: BotLoop] - Getting map of (37.973997934546, 23.735620198847794)
←[0;39m←[37m11 ┴Ϋή 09:13:52 [default: BotLoop] - Getting map of (37.97398489933362, 23.73561582614246)
←[0;39m←[37m11 ┴Ϋή 09:13:57 [default: BotLoop] - Getting map of (37.97393784421435, 23.735558590914344)
←[0;39m←[37m11 ┴Ϋή 09:14:02 [default: BotLoop] - Getting map of (37.973980615171094, 23.73560487123038)
←[0;39m←[37m11 ┴Ϋή 09:14:07 [default: BotLoop] - Getting map of (37.97395210350223, 23.73562480466841)
←[0;39m←[37m11 ┴Ϋή 09:14:12 [default: BotLoop] - Getting map of (37.97394460834926, 23.735617153529546)
←[0;39m←[37m11 ┴Ϋή 09:14:17 [default: BotLoop] - Getting map of (37.973984277730125, 23.735572738264)
←[0;39m←[35m11 ┴Ϋή 09:14:19 [default: ProfileLoop] - Profile update: 1871990 XP on LVL 29; 221990/350000 (63,43%) to LVL 30
←[0;39m←[35m11 ┴Ϋή 09:14:19 [default: ProfileLoop] - XP gain: 950 XP in 19 mins; XP rate: 3.000/hr
Pokemon caught/transferred: 2/2; Pokemon caught from lures: 0; Items caught/dropped: 12/5;
Pokebank 161/350; Stardust 634222; Inventory 850/850
←[0;39m←[37m11 ┴Ϋή 09:14:20 [default: ProfileLoop] - Wrote export.

After a restart everything is back to normal for some time again.
Now we have 2 bugs that stop the program...... :(

**Comment by pashorizer** [comment] 2016-08-11 07:50
Yeah, this is going to be fixed with https://github.com/jabbink/PokemonGoBot/commit/f31717ddab2f207b80c8c4742c99ae87b6a3eb1f

**Comment by staurakis** [comment] 2016-08-11 09:06
And a new one: 

←[0;39m←[37m11 ┴Ϋή 12:04:55 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:56 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:56 [default: BotLoop] - Getting map of (37.92852192577878, 23.686297276614162)
←[0;39m←[37m11 ┴Ϋή 12:04:57 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:57 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:58 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:58 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:59 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:04:59 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:00 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:00 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:01 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:01 [default: BotLoop] - Getting map of (37.92856748961486, 23.686376818883915)
←[0;39m←[31m11 ┴Ϋή 12:05:01 [default: BotLoop] - Error running loop BotLoop!
←[0;39m←[37m11 ┴Ϋή 12:05:01 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39mcom.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred.
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:45)
        at com.pokegoapi.api.map.Map.getCatchablePokemon(Map.java:148)
        at ink.abb.pogo.scraper.util.map.MapKt.getCatchablePokemon(Map.kt:15)
        at ink.abb.pogo.scraper.tasks.CatchOneNearbyPokemon.run(CatchOneNearbyPokemon.kt:32)
        at ink.abb.pogo.scraper.Bot.task(Bot.kt:245)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:145)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:35)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:193)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:35)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved
, token not refreshed?
        at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
        at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
        at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:37)
        ... 9 more
Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
        at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
        at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.Observable.unsafeSubscribe(Observable.java:9861)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
        at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.subscribe(Observable.java:9957)
        at rx.Observable.subscribe(Observable.java:9924)
        at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
        ... 11 more
Caused by: com.pokegoapi.exceptions.LoginFailedException: Invalid Auth status code recieved, token not refreshed?
        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:217)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:290)
        at java.lang.Thread.run(Unknown Source)
←[37m11 ┴Ϋή 12:05:02 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:03 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:03 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:04 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:04 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:05 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:05 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:06 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11
←[0;39m←[37m11 ┴Ϋή 12:05:06 [default: BotLoop] - Getting map of (37.92859523278644, 23.68635234851954)
←[0;39m←[37m11 ┴Ϋή 12:05:07 [default: PokestopLoop] - Looting nearby pokestop a89d3fe347f5436e9d9300f4a07b1742.11

The bot is stuck doing nothing all the above time.

**Comment by TerrorFactor** [comment] 2016-08-11 16:04
I seem to have the same issue. I think it started yesterday or the day before that. Not sure if it ever worked properly after the API updates.
It seems to work OK for a while and then stops. Total XP rate/hour is also very low (3k/h or so after running for an hour)

**Comment by langerhans** [comment] 2016-08-11 19:22
Duplicate of #862

**Closed by langerhans** 2016-08-11 19:22 UTC
