### ISSUE TITLE
Dropping PokeBalls?

### ISSUE THREAD

**Issue by Smir** [jabbink/PokemonGoBot#71] opened 2016-07-22 15:12 UTC
I have the drop item feature on, but surely it would drop everything else first before dropping Pokeball's especially great ones?

anyone else get this or do I have something setup wrong?

> Dropped 3x ITEM_POKE_BALL

**Comment by leadboots5** [comment] 2016-07-22 15:15
working as intended. its set to only keep 20 of them. you can make the change yourself or wait till its changed(someone is working on it).

**Comment by mroge009** [comment] 2016-07-22 16:29
In the code you can declare how much of each item you would like to keep.
I agree however that it would be nice to be able to modify this from the config file.
Ill get started on that.
```
val uselessItems = mapOf(
            Pair(ItemId.ITEM_REVIVE, 20),
            Pair(ItemId.ITEM_MAX_REVIVE, 10),
            Pair(ItemId.ITEM_POTION, 0),
            Pair(ItemId.ITEM_SUPER_POTION, 20),
            Pair(ItemId.ITEM_HYPER_POTION, 50),
            Pair(ItemId.ITEM_MAX_POTION, 50),
            Pair(ItemId.ITEM_POKE_BALL, 100),
            Pair(ItemId.ITEM_GREAT_BALL, 100),
            Pair(ItemId.ITEM_ULTRA_BALL, 100),
            Pair(ItemId.ITEM_MASTER_BALL, 10),
            Pair(ItemId.ITEM_RAZZ_BERRY, 30)
    )
```

**Comment by mroge009** [comment] 2016-07-22 16:39
Config.properties
```
# Amount of useless items to keep
ITEM_REVIVE=20
ITEM_MAX_REVIVE=0
ITEM_POTION=0
ITEM_SUPER_POTION=20
ITEM_HYPER_POTION=20
ITEM_MAX_POTION=20
ITEM_POKE_BALL=100
ITEM_GREAT_BALL=100
ITEM_ULTRA_BALL=100
ITEM_MASTER_BALL=100
ITEM_RAZZ_BERRY=30

Settings.kt
```
val uselessItems = mapOf(
            Pair(ItemId.ITEM_REVIVE, getPropertyIfSet("Amount of useless items to keep", "ITEM_REVIVE", 20, String::toInt)),
            Pair(ItemId.ITEM_MAX_REVIVE, getPropertyIfSet("Amount of useless items to keep", "ITEM_MAX_REVIVE", 10, String::toInt)),
            Pair(ItemId.ITEM_POTION, getPropertyIfSet("Amount of useless items to keep", "ITEM_POTION", 0, String::toInt)),
            Pair(ItemId.ITEM_SUPER_POTION, getPropertyIfSet("Amount of useless items to keep", "ITEM_SUPER_POTION", 30, String::toInt)),
            Pair(ItemId.ITEM_HYPER_POTION, getPropertyIfSet("Amount of useless items to keep", "ITEM_HYPER_POTION", 50, String::toInt)),
            Pair(ItemId.ITEM_MAX_POTION, getPropertyIfSet("Amount of useless items to keep", "ITEM_MAX_POTION", 50, String::toInt)),
            Pair(ItemId.ITEM_POKE_BALL, getPropertyIfSet("Amount of useless items to keep", "ITEM_POKE_BALL", 50, String::toInt)),
            Pair(ItemId.ITEM_GREAT_BALL, getPropertyIfSet("Amount of useless items to keep", "ITEM_GREAT_BALL", 50, String::toInt)),
            Pair(ItemId.ITEM_ULTRA_BALL, getPropertyIfSet("Amount of useless items to keep", "ITEM_ULTRA_BALL", 50, String::toInt)),
            Pair(ItemId.ITEM_MASTER_BALL, getPropertyIfSet("Amount of useless items to keep", "ITEM_MASTER_BALL", 10, String::toInt)),
            Pair(ItemId.ITEM_RAZZ_BERRY, getPropertyIfSet("Amount of useless items to keep", "ITEM_RAZZ_BERRY", 50, String::toInt))
    )
```
```

**Comment by KyleBoyer** [comment] 2016-07-22 18:15
Has this been implemented/merged with the main branch?

**Comment by CosmoRing** [comment] 2016-07-22 18:36
Not yet, waiting for @jabbink approval.

**Comment by kasagon** [comment] 2016-07-22 19:18
It would be nice if we could adjust those settings in the config.properties file.

**Comment by Smir** [comment] 2016-07-22 19:52
it's just waiting approval kasagon :)

**Comment by elliottfeng** [comment] 2016-07-22 22:44
same idea with mine. try it on.

**Comment by jabbink** [comment] 2016-07-22 23:37
implemented on `master`

**Closed by jabbink** 2016-07-22 23:37 UTC
