### ISSUE TITLE
Null Pointer exception after D/RequestHandler

### ISSUE THREAD

**Issue by harpon** [jabbink/PokemonGoBot#881] opened 2016-08-09 02:32 UTC
**Description:**
D/RequestHandler: Authenticated with static token
Exception in thread "default" java.lang.NullPointerException
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:41)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:142)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:84)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Version:**
jar file 5.0

**Operating System:**
OSX 10.1

**Java version:**
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by harpon** [comment] 2016-08-09 02:33
anyone can help? please..

**Comment by chaoen** [comment] 2016-08-09 17:32
same issue

**Comment by Cypherke** [comment] 2016-08-09 18:34
dod you try version 5.1?

**Comment by langerhans** [comment] 2016-08-11 18:57
Duplicate of #794. search existing issues before opening new ones, please.

**Closed by langerhans** 2016-08-11 18:57 UTC
