### ISSUE TITLE
Doesn't work at all...

### ISSUE THREAD

**Issue by ColeB27** [jabbink/PokemonGoBot#43] opened 2016-07-22 04:31 UTC
Tried to use it. Receive no pokestops/nothing.

C:\Users\coleb\Desktop\test>java -jar pogo.scraper-all-0.2.1.jar
Logged in as mattlead
Get default data from pogo server.Context built!
Pokecoin: 60
Stardust: 1133
Level 16, Experience 123209
Getting map of 42.3601 71.0589
Getting initial pokestops..
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17
Getting map of 42.3601 71.0589
Profile update : 123209 XP on LVL 16; 23209/40000 (58.02%) to LVL 17

**Comment by ColeB27** [comment] 2016-07-22 04:55
It works in paris, but not USA!

**Comment by MarceloAlves** [comment] 2016-07-22 05:42
@ColeB27 are you sure those are the coordinates you want? that location is in Krygyzstan. I stil with this [website](http://mygeoposition.com/). Set the point and hit `copy(x,y)` and use that for your lat/lng

**Comment by Spyderdreams** [comment] 2016-07-22 05:44
I used it in Oklahoma, Vegas and Tokyo. All works good. tested with google account and Pokemon club login.

**Comment by LordMalkev** [comment] 2016-07-22 06:58
Looks like a soft ban. If you have the account open in your device and then open it on PC, you get a soft ban and don't receive xp for half an hour.

**Comment by jabbink** [comment] 2016-07-22 08:26
Duplicate of #21

**Closed by jabbink** 2016-07-22 08:26 UTC
