### ISSUE TITLE
Same error 0.5.0 alpha3 BotLoop

### ISSUE THREAD

**Issue by alone23** [jabbink/PokemonGoBot#660] opened 2016-07-30 19:35 UTC
30 jul 21:31:28: Error running loop BotLoop! 
kotlin.TypeCastException: null cannot be cast to non-null type com.pokegoapi.api.map.fort.Pokestop
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:132)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
30 jul 21:31:31: Error running loop BotLoop! 
kotlin.TypeCastException: null cannot be cast to non-null type com.pokegoapi.api.map.fort.Pokestop
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:132)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
30 jul 21:31:36: Error running loop BotLoop! 
kotlin.TypeCastException: null cannot be cast to non-null type com.pokegoapi.api.map.fort.Pokestop
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:132)
        at ink.abb.pogo.scraper.Bot$start$4.invoke(Bot.kt:34)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:163)
        at ink.abb.pogo.scraper.Bot$runLoop$1.invoke(Bot.kt:34)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

Not fixed

Anyone can check it again?

Thanks!

**Comment by alone23** [comment] 2016-07-30 19:52
Same error with limit speed/delay

**Comment by superkilerpokemon** [comment] 2016-07-30 20:25
Can confirm. 
Whenever I start the bot it works without any problems for 30min-60min. After this time period it gives me the Bootloop error.

**Comment by alone23** [comment] 2016-07-30 20:39
My errors occurs just start bot

**Comment by pashorizer** [comment] 2016-07-30 20:43
Yes, that is fixed with this https://github.com/jabbink/PokemonGoBot/commit/62e2fb11eeebf52bcacffcb9e0b4c04fe634d68d

**Comment by superkilerpokemon** [comment] 2016-07-30 20:44
how exactly do I implement this? ^^

**Comment by pashorizer** [comment] 2016-07-30 20:46
@superkilerpokemon Yeah, it's fixed with this https://github.com/jabbink/PokemonGoBot/commit/62e2fb11eeebf52bcacffcb9e0b4c04fe634d68d
To implement that, you have to compile the dev branch or wait till a new jar is getting uploaded

**Comment by rannmann** [comment] 2016-07-30 22:08
I only ran into this with custom pathing, where it was travelling a large (new) distance fairly quickly.  But I only ran into it once.  Not sure if it was coincidence or related.

Haven't seen it since 62e2fb1 though.

**Comment by kasagon** [comment] 2016-07-30 23:31
I still have those Botloop and Walkingloop errors in 62e2fb1 ..

**Comment by pashorizer** [comment] 2016-07-30 23:43
@kasagon Yeah, these exceptions are API related since some got changed. We did not adjust them right now, but they do not crash the bot or hinder it in any serious way.

**Comment by kasagon** [comment] 2016-07-31 19:02
@pashorizer I think it is something with the login thing as well, since I am getting this error over and over right now:

    D/RequestHandler: Authenticated with static token
    31 jul 21:01:18: Error running loop BotLoop! com.pokegoapi.exceptions.LoginFailedException: Error  in API Url


        at com.pokegoapi.main.RequestHandler.internalSendServerRequests(RequestHandler.java:216)
        at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pashorizer** [comment] 2016-07-31 19:34
@kasagon restart the bot

**Comment by langerhans** [comment] 2016-07-31 20:05
Can't reproduce anymore in latest release, closing.

**Closed by langerhans** 2016-07-31 20:05 UTC
Labels: bug
