### ISSUE TITLE
pogo.scraper-all-0.5.0-alpha2 Error with Google.

### ISSUE THREAD

**Issue by Nicolr3** [jabbink/PokemonGoBot#615] opened 2016-07-29 01:20 UTC
I can not access with Google account
![8d46ab6fc798b428243fd3f15db21119](https://cloud.githubusercontent.com/assets/6991295/17234655/36cf02c0-553b-11e6-9c3c-b51300247b26.png)

![f6b5d6c154c7666ec99fa30fc2b097e3](https://cloud.githubusercontent.com/assets/6991295/17234681/66a67bae-553b-11e6-9a1b-851f176687a0.png)

**Comment by Emuuung** [comment] 2016-07-29 02:05
Please close this issue as it is a duplicate.

**Comment by Skander1998** [comment] 2016-07-29 04:08
Disable 2 factor auth OR use an app password (Google security settings, allows you to bypass 2 auth for an app).

Close.

**Comment by langerhans** [comment] 2016-07-29 07:00
Duplicate of #583

**Closed by langerhans** 2016-07-29 07:00 UTC
