### ISSUE TITLE
Items caught are lowering

### ISSUE THREAD

**Issue by DieterrrP** [jabbink/PokemonGoBot#1115] opened 2016-08-16 14:25 UTC
**Description:**
Hi, my total amounts of items is lowering, but the bot says that it's capturing more than dropping. E.g. for the latest walk: Items caught/dropped: 59/11 - Inventory 218/350 (started at 225/350).

I know that balls are thrown, but there is plenty of room to fill the inventory since the max number in the properties file is filled out correctly.

**Expected behavior:**
The inventory is decreasing, while it should rise.

**Actual behavior:**
No normal balls anymore, whilst the max number of balls is at 40

**Version:**
0.6.0

**Operating System:**
OS X Yosemite

**Java version:**
Java 8 update 101

Leave this sentence in your issue as proof that you have read and used this template.

**Comment by classicalDonkey** [comment] 2016-08-16 14:33
I have been getting this too...one day I had like 100 potions and etc and the next day none and was working fine before

**Comment by Sieberkev** [comment] 2016-08-24 21:51
Do you have in your configuration group_items_by_type=true``?

**Comment by DieterrrP** [comment] 2016-08-25 07:14
It was on 'false'. Account = banned, with a new one I don't have that problem.

**Comment by Sieberkev** [comment] 2016-08-25 07:54
It's possible that the underlying API didn't update the inventory correct, but that will (hopefully) be fixed soon with the new API.

If you can't reproduce this on your new account, please close the issue :)

**Closed** 2016-08-25 08:41 UTC
