### ISSUE TITLE
Problem with the comeback

### ISSUE THREAD

**Issue by lBeher** [jabbink/PokemonGoBot#867] opened 2016-08-08 21:30 UTC
I've founded a problem while running the bot. I have in the config to come back at the first PokeStop every 300 meters and 40 seconds, but when the bot has been runing for 10-15 minutes suddenly this stop working more and dont come back any more. How can I fix it? Maybe the error of my previous post is because of this.

WHEN ITS WORKING

08 ago 22:46:24 (default: BotLoop): Getting map of (37.80872816162275, -122.4100057321242)
08 ago 22:46:24 (default: BotLoop): Going to transfer MAGIKARP with CP 65 and IV 68%; reason: CP < 1000 and IV < 90% 
**08 ago 22:46:25 (default: WalkingLoop): Starting Pokestop reached in 40 steps. 
08 ago 22:46:29 (default: WalkingLoop): Starting Pokestop reached in 20 steps.** 
08 ago 22:46:29 (default: BotLoop): Getting map of (37.808687085289975, -122.40979145426886)
**08 ago 22:46:33 (default: WalkingLoop): Starting Pokestop reached in 0 steps. 
08 ago 22:46:33 (default: WalkingLoop): Starting Pokestop reached in 0 steps.**

NO WORKING

08 ago 23:17:06 (default: BotLoop): Getting map of (37.80871054555023, -122.40971480747987)
08 ago 23:17:11 (default: BotLoop): Getting map of (37.80875367296981, -122.40968908038343)
08 ago 23:17:16 (default: BotLoop): Getting map of (37.80870957899918, -122.40971621744714)
08 ago 23:17:21 (default: BotLoop): Getting map of (37.80875835574444, -122.4096613166375)
08 ago 23:17:26 (default: BotLoop): Getting map of (37.8087394163088, -122.40968049203948)
08 ago 23:17:31 (default: BotLoop): Getting map of (37.8087499144737, -122.4096825976999)
08 ago 23:17:36 (default: BotLoop): Getting map of (37.80878020191273, -122.4097390774403)
08 ago 23:17:41 (default: BotLoop): Getting map of (37.80871546924261, -122.40971701468465)
08 ago 23:17:43 (default: ProfileLoop): Profile update: 785847 XP on LVL 25; 75847/190000 (39,92%) to LVL 26 
08 ago 23:17:43 (default: ProfileLoop): XP gain: 20790 XP; Pokemon caught/transferred: 89/83; Pokemon caught from lures: 53; Items caught/dropped: 92/17;
Pokebank 155/250; Stardust 23087; Inventory 125/350 
08 ago 23:17:46 (default: BotLoop): Getting map of (37.80878115662539, -122.40971943584951)
08 ago 23:17:51 (default: BotLoop): Getting map of (37.80877957630486, -122.40974896533623)
08 ago 23:17:56 (default: BotLoop): Getting map of (37.808766326574634, -122.4096803955088)
08 ago 23:18:01 (default: BotLoop): Getting map of (37.808690170198346, -122.40970366387981)
08 ago 23:18:06 (default: BotLoop): Getting map of (37.808769588279425, -122.40967985268456)
08 ago 23:18:11 (default: BotLoop): Getting map of (37.808686504020564, -122.40974256111853)
08 ago 23:18:16 (default: BotLoop): Getting map of (37.8087338128476, -122.40965845295614)
08 ago 23:18:21 (default: BotLoop): Getting map of (37.80878228182591, -122.40967174548935)

**Comment by lBeher** [comment] 2016-08-08 22:40
I think the error: 

**Error running loop BotLoop!** 

Its because of this. Can anyone tell me how to fix it? It's very strange.. the bot works perfect but suddenly stop coming back to the first Pokestop, I dont understand why this happen.

**Comment by zby920415** [comment] 2016-08-10 01:32
I have the same issue!! It forces me to restart per hour

**Comment by langerhans** [comment] 2016-08-11 18:52
Duplicate of 862. Also it might be an issue where it stops after getting one exception. Restarting the bot usually fixes that.

**Closed by langerhans** 2016-08-11 18:52 UTC
