### ISSUE TITLE
I'm getting Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url

### ISSUE THREAD

**Issue by kajeagentspi** [jabbink/PokemonGoBot#310] opened 2016-07-25 13:12 UTC
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url
        at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
        at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
        at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
        at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
        at ink.abb.pogo.scraper.MainKt.main(Main.kt:107)

**Comment by jabbink** [comment] 2016-07-25 13:12
Duplicate of #165 and fixed when you compile from source

**Comment by ColeB27** [comment] 2016-07-25 13:13
Looks like an error with the login, maybe wrong password/servers down.

**Comment by jabbink** [comment] 2016-07-25 13:13
Fix is to remove the token from the config

**Closed** 2016-07-25 13:12 UTC

**Comment by kajeagentspi** [comment] 2016-07-25 13:18
Thanks for the reply and this bot.
