### ISSUE TITLE
[Question] Is it safe to open the bot after the latest update?

### ISSUE THREAD

**Issue by alexvkcr** [jabbink/PokemonGoBot#1330] opened 2016-11-21 12:24 UTC
Leave this sentence in your issue as proof that you have read and used this template.

I opened my phone and boom, new Pokemon version today.

Does that mean that it is not safe to open the bot until new release appears?

Thanks!

**Comment by matthiasjo** [comment] 2016-11-21 12:34
Yes, thats exactly what it means. The bot is easily detectable when using the old API. So we have to wait until the devs do their magic. That takes time and patience.

**Comment by alexvkcr** [comment] 2016-11-21 12:35
Thanks for the quick answer! @Mazerunner04

**Comment by jacc** [comment] 2016-11-21 13:03
It's usually a week or so before the RE's get the API cracked, and less than a day for @jabbink to integrate it into the bot.

**Comment by alexvkcr** [comment] 2016-11-21 13:05
No amount of patience can match up the work of these people, awesome job!

**Comment by alexvkcr** [comment] 2016-11-24 08:23
I saw the lattest commit and it's an update to in API version, if I download the code and compile it, will it be no longer detectable by Niantic?

**Comment by Cypherke** [comment] 2016-11-24 12:01
no that api is still based on 0.45 and 0.47 is forced by Niantic, which is still not ready

**Comment by alexvkcr** [comment] 2016-11-28 13:18
Any news? T.T

**Comment by osupapercilp** [comment] 2016-12-04 16:31
Any updates? or is this considered dead :(

**Comment by jabbink** [comment] 2016-12-05 10:43
Duplicate of #1298

Just wait.

**Closed as completed by jabbink** 2016-12-05 10:43 UTC
Labels: duplicate, Search before posting
