### ISSUE TITLE
Longitude Latitude Error

### ISSUE THREAD

**Issue by ilhamhamid** [jabbink/PokemonGoBot#1070] opened 2016-08-14 17:16 UTC
My bot keep on adding letter 'z' to the end of the longitude latitude. It can't detect any real locations. Help? Thanks a lot mate!

**Comment by ilhamhamid** [comment] 2016-08-14 17:17
15 Aug 00:07:53 [default] - Retrying in 10 seconds...
15 Aug 00:08:03 [default] - Got 0 pokestops
15 Aug 00:08:03 [default] - Retrying in 10 seconds...
15 Aug 00:08:14 [default] - Got 0 pokestops
15 Aug 00:08:14 [default] - Decreasing initialMapSize to 7
15 Aug 00:08:14 [default] - Retrying in 10 seconds...
15 Aug 00:08:25 [default] - Got 0 pokestops
15 Aug 00:08:25 [default] - Retrying in 10 seconds...
15 Aug 00:08:35 [default] - Got 0 pokestops
15 Aug 00:08:35 [default] - Retrying in 10 seconds...
15 Aug 00:08:46 [default] - Got 0 pokestops
15 Aug 00:08:46 [default] - Decreasing initialMapSize to 5
15 Aug 00:08:46 [default] - Retrying in 10 seconds...
15 Aug 00:08:57 [default] - Got 0 pokestops
15 Aug 00:08:57 [default] - Retrying in 10 seconds...
15 Aug 00:09:07 [default] - Got 0 pokestops
15 Aug 00:09:07 [default] - Retrying in 10 seconds...
15 Aug 00:09:18 [default] - Got 0 pokestops
15 Aug 00:09:18 [default] - Decreasing initialMapSize to 3
15 Aug 00:09:18 [default] - Retrying in 10 seconds...
15 Aug 00:09:28 [default] - Got 0 pokestops
15 Aug 00:09:28 [default] - Retrying in 10 seconds...
15 Aug 00:09:39 [default] - Got 0 pokestops
15 Aug 00:09:39 [default] - Retrying in 10 seconds...
15 Aug 00:09:49 [default] - Got 0 pokestops
15 Aug 00:09:49 [default] - Decreasing initialMapSize to 1
15 Aug 00:09:49 [default] - Retrying in 10 seconds...
15 Aug 00:10:00 [default] - Got 0 pokestops
15 Aug 00:10:00 [default] - Retrying in 10 seconds...
15 Aug 00:10:10 [default] - Got 0 pokestops
15 Aug 00:10:10 [default] - Retrying in 10 seconds...
15 Aug 00:10:21 [default] - Got 0 pokestops
15 Aug 00:10:21 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:10:21 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:10:21 [default] - Retrying in 10 seconds...
15 Aug 00:10:31 [default] - Got 0 pokestops
15 Aug 00:10:31 [default] - Retrying in 10 seconds...
15 Aug 00:10:42 [default] - Got 0 pokestops
15 Aug 00:10:42 [default] - Retrying in 10 seconds...
15 Aug 00:10:52 [default] - Got 0 pokestops
15 Aug 00:10:52 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:10:52 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:10:52 [default] - Retrying in 10 seconds...
15 Aug 00:11:03 [default] - Got 0 pokestops
15 Aug 00:11:03 [default] - Retrying in 10 seconds...
15 Aug 00:11:13 [default] - Got 0 pokestops
15 Aug 00:11:13 [default] - Retrying in 10 seconds...
15 Aug 00:11:24 [default] - Got 0 pokestops
15 Aug 00:11:24 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:11:24 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:11:24 [default] - Retrying in 10 seconds...
15 Aug 00:11:34 [default] - Got 0 pokestops
15 Aug 00:11:34 [default] - Retrying in 10 seconds...
15 Aug 00:11:45 [default] - Got 0 pokestops
15 Aug 00:11:45 [default] - Retrying in 10 seconds...
15 Aug 00:11:55 [default] - Got 0 pokestops
15 Aug 00:11:55 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:11:55 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:11:55 [default] - Retrying in 10 seconds...
15 Aug 00:12:06 [default] - Got 0 pokestops
15 Aug 00:12:06 [default] - Retrying in 10 seconds...
15 Aug 00:12:17 [default] - Got 0 pokestops
15 Aug 00:12:17 [default] - Retrying in 10 seconds...
15 Aug 00:12:27 [default] - Got 0 pokestops
15 Aug 00:12:27 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:12:27 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:12:27 [default] - Retrying in 10 seconds...
15 Aug 00:12:38 [default] - Got 0 pokestops
15 Aug 00:12:38 [default] - Retrying in 10 seconds...
15 Aug 00:12:48 [default] - Got 0 pokestops
15 Aug 00:12:48 [default] - Retrying in 10 seconds...
15 Aug 00:12:59 [default] - Got 0 pokestops
15 Aug 00:12:59 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:12:59 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:12:59 [default] - Retrying in 10 seconds...
15 Aug 00:13:09 [default] - Got 0 pokestops
15 Aug 00:13:09 [default] - Retrying in 10 seconds...
15 Aug 00:13:19 [default] - Got 0 pokestops
15 Aug 00:13:19 [default] - Retrying in 10 seconds...
15 Aug 00:13:30 [default] - Got 0 pokestops
15 Aug 00:13:30 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:13:30 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:13:30 [default] - Retrying in 10 seconds...
15 Aug 00:13:40 [default] - Got 0 pokestops
15 Aug 00:13:40 [default] - Retrying in 10 seconds...
15 Aug 00:13:51 [default] - Got 0 pokestops
15 Aug 00:13:51 [default] - Retrying in 10 seconds...
15 Aug 00:14:01 [default] - Got 0 pokestops
15 Aug 00:14:01 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:14:01 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:14:01 [default] - Retrying in 10 seconds...
15 Aug 00:14:12 [default] - Got 0 pokestops
15 Aug 00:14:12 [default] - Retrying in 10 seconds...
15 Aug 00:14:22 [default] - Got 0 pokestops
15 Aug 00:14:22 [default] - Retrying in 10 seconds...
15 Aug 00:14:33 [default] - Got 0 pokestops
15 Aug 00:14:33 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:14:33 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:14:33 [default] - Retrying in 10 seconds...
15 Aug 00:14:43 [default] - Got 0 pokestops
15 Aug 00:14:43 [default] - Retrying in 10 seconds...
15 Aug 00:14:54 [default] - Got 0 pokestops
15 Aug 00:14:54 [default] - Retrying in 10 seconds...
15 Aug 00:15:04 [default] - Got 0 pokestops
15 Aug 00:15:04 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:15:04 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:15:04 [default] - Retrying in 10 seconds...
15 Aug 00:15:15 [default] - Got 0 pokestops
15 Aug 00:15:15 [default] - Retrying in 10 seconds...
15 Aug 00:15:25 [default] - Got 0 pokestops
15 Aug 00:15:25 [default] - Retrying in 10 seconds...
15 Aug 00:15:36 [default] - Got 0 pokestops
15 Aug 00:15:36 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:15:36 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:15:36 [default] - Retrying in 10 seconds...
15 Aug 00:15:46 [default] - Got 0 pokestops
15 Aug 00:15:46 [default] - Retrying in 10 seconds...
15 Aug 00:15:57 [default] - Got 0 pokestops
15 Aug 00:15:57 [default] - Retrying in 10 seconds...
15 Aug 00:16:07 [default] - Got 0 pokestops
15 Aug 00:16:07 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:16:07 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:16:07 [default] - Retrying in 10 seconds...
15 Aug 00:16:18 [default] - Got 0 pokestops
15 Aug 00:16:18 [default] - Retrying in 10 seconds...
15 Aug 00:16:28 [default] - Got 0 pokestops
15 Aug 00:16:28 [default] - Retrying in 10 seconds...
15 Aug 00:16:39 [default] - Got 0 pokestops
15 Aug 00:16:39 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:16:39 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:16:39 [default] - Retrying in 10 seconds...
15 Aug 00:16:49 [default] - Got 0 pokestops
15 Aug 00:16:49 [default] - Retrying in 10 seconds...
15 Aug 00:17:00 [default] - Got 0 pokestops
15 Aug 00:17:00 [default] - Retrying in 10 seconds...
15 Aug 00:17:10 [default] - Got 0 pokestops
15 Aug 00:17:10 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:17:10 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:17:10 [default] - Retrying in 10 seconds...
15 Aug 00:17:21 [default] - Got 0 pokestops
15 Aug 00:17:21 [default] - Retrying in 10 seconds...
15 Aug 00:17:31 [default] - Got 0 pokestops
15 Aug 00:17:31 [default] - Retrying in 10 seconds...

**Comment by ilhamhamid** [comment] 2016-08-14 17:18
15 Aug 00:17:10 [default] - Cannot decrease initialMapSize even further. Are your sure your latitude/longitude is correct?
15 Aug 00:17:10 [default] - This is what I am trying to fetch: https://www.google.com/maps/@40.7829,73.9654,15z
15 Aug 00:17:10 [default] - Retrying in 10 seconds...
15 Aug 00:17:21 [default] - Got 0 pokestops
15 Aug 00:17:21 [default] - Retrying in 10 seconds...
15 Aug 00:17:31 [default] - Got 0 pokestops
15 Aug 00:17:31 [default] - Retrying in 10 seconds...
1

**Comment by AlexBoulyga** [comment] 2016-08-14 17:20
What is in your settings file?

**Comment by Venome** [comment] 2016-08-14 17:55
that is zoom level

**Comment by ReignOfComputer** [comment] 2016-08-14 21:39
Coordinates seem to be in the middle of a mountain, are you sure there's anything in that area?

The '15z' at the end [is by design](https://github.com/jabbink/PokemonGoBot/blob/develop/src/main/kotlin/ink/abb/pogo/scraper/Bot.kt#L120), as mentioned it's the zoom level on Google Maps.

**Comment by jabbink** [comment] 2016-08-14 21:48
OP entered useles coords. Closing

**Closed by jabbink** 2016-08-14 21:48 UTC
