### ISSUE TITLE
Error: Accepting ToS

### ISSUE THREAD

**Issue by watsonVon** [jabbink/PokemonGoBot#1089] opened 2016-08-15 12:51 UTC
I have a Pokemon trainer account, since yesterday i can not start the bot anymore:

15 Aug 14:47:47 [default] - Accepting ToS
Exception in thread "default" java.lang.NullPointerException
	at ink.abb.pogo.scraper.Bot.<init>(Bot.kt:43)
	at ink.abb.pogo.scraper.MainKt.startBot(Main.kt:294)
	at ink.abb.pogo.scraper.MainKt.startDefaultBot(Main.kt:145)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:57)
	at ink.abb.pogo.scraper.PokemonGoBotApplication$BotRunner$run$1.invoke(PokemonGoBotApplication.kt:46)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)

**Comment by Sieberkev** [comment] 2016-08-15 13:01
Bad news: Your account is banned

**Comment by watsonVon** [comment] 2016-08-15 13:10
Interesting. Can you elaborate this any further ? I thought there is only a soft ban ?

**Comment by muschter** [comment] 2016-08-15 13:13
There is a thread on /r/PokemonGoDev that goes into more detail, but if you catch more than 1k Pokemon or spin 2k Pokestops in a certain window of time, your account gets flagged.

**Comment by Sieberkev** [comment] 2016-08-15 13:22
> I thought there is only a soft ban ?

Several accounts got already perma banned, but afaik there's no fixed reason why. I had the same on my main account, when I checked it out with the API i found out my profile is still intact (playername/level/xp/...) but all items/pokes/... got removed. You can't login to the official client too, you just get an error since banning is not even build in in the client yet ^_^

**Comment by watsonVon** [comment] 2016-08-15 13:31
I can confirm that i can not log in with the official client. Well well....

**Comment by Sieberkev** [comment] 2016-08-15 13:36
I'll close this since it is not a bug on the bot. Sorry for the loss of your account tho!

**Closed by Sieberkev** 2016-08-15 13:36 UTC
Labels: Account banned
