### ISSUE TITLE
How do you implement a refresh token

### ISSUE THREAD

**Issue by cwliias** [jabbink/PokemonGoBot#282] opened 2016-07-25 08:25 UTC
How do you implement a refresh token so the bot stops crashing every 3 or 4 hours? A step by step tut would be nice, I'm a nub

**Comment by jabbink** [comment] 2016-07-25 09:05
Try removing the token behind `token=` in the config and see if that fixes it.

Otherwise: duplicate of #165

**Closed by jabbink** 2016-07-25 09:05 UTC
