### ISSUE TITLE
How To Fix build Failed

### ISSUE THREAD

**Issue by Jobzakung** [jabbink/PokemonGoBot#1121] opened 2016-08-16 19:16 UTC
:test

ink.abb.pogo.scraper.TestSettings > testDefaultSettings FAILED
    java.io.FileNotFoundException at TestSettings.kt:25

ink.abb.pogo.scraper.TestSettings > testTemplateKeys FAILED
    java.io.FileNotFoundException at TestSettings.kt:73

2 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

**Expected behavior:**
[What should happen?]

**Actual behavior:**
[17 Aug 02:08:03 [default] - Getting initial pokestops...
       17 Aug 02:08:04 [default] - Got 0 pokestops
17 Aug 02:08:04 [default] - Retrying in 10 seconds...
       17 Aug 02:08:15 [default] - Got 0 pokestops
17 Aug 02:08:15 [default] - Retrying in 10 seconds...
       17 Aug 02:08:26 [default] - Got 0 pokestops
17 Aug 02:08:26 [default] - Decreasing initialMapSize to 7
17 Aug 02:08:26 [default] - Retrying in 10 seconds...
       17 Aug 02:08:40 [default] - Got 0 pokestops
17 Aug 02:08:40 [default] - Retrying in 10 seconds...
       17 Aug 02:08:52 [default] - Got 0 pokestops
17 Aug 02:08:52 [default] - Retrying in 10 seconds...
       17 Aug 02:09:03 [default] - Got 0 pokestops
17 Aug 02:09:03 [default] - Decreasing initialMapSize to 5
17 Aug 02:09:03 [default] - Retrying in 10 seconds...
       17 Aug 02:09:15 [default] - Got 0 pokestops
17 Aug 02:09:15 [default] - Retrying in 10 seconds...
       17 Aug 02:09:27 [default] - Got 0 pokestops
17 Aug 02:09:27 [default] - Retrying in 10 seconds...
       17 Aug 02:09:38 [default] - Got 0 pokestops
17 Aug 02:09:38 [default] - Decreasing initialMapSize to 3
17 Aug 02:09:38 [default] - Retrying in 10 seconds...
       17 Aug 02:09:49 [default] - Got 0 pokestops
17 Aug 02:09:49 [default] - Retrying in 10 seconds...]

**Version:**
[PokemonGoBot-0.6.0.jar]

**Operating System:**
[linux]

**Java version:**
1.8.0_101`]

**Comment by jabbink** [comment] 2016-08-16 19:20
Hi @Jobzakung,

It looks like there is some information missing from your ticket that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Contribution Guidelines](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/CONTRIBUTING.md) and [default Issue template (the one you did not follow)](https://github.com/jabbink/PokemonGoBot/blob/develop/.github/ISSUE_TEMPLATE.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next two days (until 2016-08-18 21:20) I'll close this ticket so it doesn't clutter the bug tracker.

Best regards,
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by AlexBoulyga** [comment] 2016-08-17 04:42
2 failed tests - have you deleted the .template file? And about the error de need More information. Is the ACC Banned?

**Comment by jabbink** [comment] 2016-08-19 19:25
Since apparently some of the required information is still missing, I'm closing this now, sorry. Feel free to reopen this or create a new issue once you can provide **all** required information.

**Closed by jabbink** 2016-08-19 19:25 UTC
Labels: incomplete issue

**Comment by pdonon** [comment] 2016-10-05 19:41
Description: Bot not finding any pokestop around : 41.385057189360005, 2.1734345939101507

Steps to reproduce:

Start the bot with : 
`timeout 3600 java -jar PokemonGoBot-0.6.0.jar`

With config : 
`# PTC/Google login credentials
username=XXXXXXX

# Choose plaintext or base64'd password
password=XXXXXX

# Token to login directly
# token=
latitude=41.385064
longitude=2.173403

# Desired probability to catch Pokemon with 1 throw
desired_catch_probability=0.4

# Desired probability to catch unwanted Pokemon (obligatory_transfer; low IV; low CP)
# Set to -1 to not attempt catching at all
desired_catch_probability_unwanted=0.0

# Set if random ball throws should be enabled
# Currently decides if the throw is nice/great/excellent/normal by using the desired_catch_probability(_unwanted), decreasing earned exp and fang rate however
# Heavily depends on the desired catch rates now, if you have too few excellent/great throws try increasing those values
random_ball_throws=false

# Set if you want to wait a little between throws (0-3 secs)
wait_between_throws=true

# Number of nearest unused pokestops to randomly select
# The next pokestop from (1/infinite)
random_next_pokestop_selection=5

# Should the bot camp around lured x pokestops (-1 = off; 1 = one needs to be in range; 2 = two..., etc)
camp_lure_pokestop=-1

## Walking
# Meters per second
speed=2.2

# Random speed range around the original speed value in Meters per Second
# Example: If speed is 2.8, and the range 0.5, the speed will be between 2.3 and 3.3
random_speed_range=0.5

# Should the bot follow the streets (true) or just go directly to pokestops/waypoints
follow_streets=true

# Should the bot loot the pokestops (true/false)
loot_pokestop=true

# Should the bot catch pokemons (true/false)
catch_pokemon=true

# Should the bot auto fill incubators with eggs (true/false)
auto_fill_incubator=true

## Items drop
# Should the bot EVER drop items (true/false)
drop_items=true

# Max number of each item that the bot should keep if "drop_items" is enabled
# Use -1 in an item to never drop this specific item
# The default values add up to 350
item_revive=20
item_max_revive=10
item_potion=0
item_super_potion=30
item_hyper_potion=50
item_max_potion=50
item_poke_ball=40
item_great_ball=50
item_ultra_ball=50
item_master_ball=10
item_razz_berry=40
item_lucky_egg=-1
item_incense=-1
item_lure_module=-1

# Groups the items that are kept by type so it keeps best of same type
# Ex: if you have item_revive=20 and item_max_revive=10 and set this
#   to true, if you get 25 item_revive and 20 item_max_revive it will
#   drop 15 item_revive and keep 10 item_revive and 20 item_max_revive
# Items that have -1 are excluded from groups
# Ex: if you set item_potion=-1 it will only group the other potions and
#   ignore item_potion (never dropping item_potion)
group_items_by_type=false

## Extra Info
# Should the bot display rewards pokestop (true/false)
display_pokestop_rewards=true

# Should the bot display if it caught a pokemon from a lure (true/false)
display_if_pokemon_from_lure=true

# Should the bot display rewards when catching pokemon (true/false)
display_pokemon_catch_rewards=true

# Display keepalive coordinates
display_keepalive=true

# Should the bot display information of where it's walking to (true/false)
# This will show the name of the pokestop that it's walking to and
#   replace on the loot log the pokestop id for its name
# WARNING:  this will increase the https requests without any need. If
#           the servers are slow it's recommended to turn off this setting
display_pokestop_name=false

## Pokemon Transfer
# Should the bot auto transfer duplicate pokemon
autotransfer=true

# Minimum amount of pokemon type to keep
keep_pokemon_amount=1

# Maximum amount of pokemon type to keep (-1 to keep all)
max_pokemon_amount=-1

# Sort by IV first instead of CP
sort_by_iv=false

# Rate for bot to throw a curveball, between 0 (never) and 1 (always)
desired_curve_rate=0.0

# Never use berries
never_use_berries=true

# Allow leaving the starting area
allow_leave_start_area=false

# Max distance from starting point the bot should ever go in meters
# (-1: only limited by the initial pokestops (~3*3km); with allow_leave_start_area=true unlimited)
spawn_radius=-1

# Number of times the pokestop should be spun to attempt softban bypass (0 to disable, 40 recommended value to work)
ban_spin_count=0

# Set timer in seconds to go back to the starting pokestop (-1 disabled)
timer_walk_to_start_pokestop=-1

# Set profile update timer (Default: 60)
profile_update_timer=60

# Minimum IV percentage to keep a pokemon (to ignore IV: use -1)
# between 0 and 100, suggested 80
transfer_iv_threshold=80

# Minimum CP to keep a pokemon (to ignore CP: use -1)
transfer_cp_threshold=400

# Minimum CP % in relation to max CP of pokemon to your current trainer lvl to keep pokemon (to disable CP%:use -1)
# e.g. Trainer lvl is 33, captured EEVEE has 490 CP which results in max possible CP of 984 with 15/14/15 IV
# that however is below the threshold of 60% because its 49%
transfer_cp_min_threshold=-1

# List of pokemon you don't want to transfer regardless of CP
# The names must be divided by a ","
# If you want all pokemons to be transferred just leave it blank
ignored_pokemon=EEVEE,MEWTWO,CHARMANDER

# List of pokemon you always want to transfer regardless of CP
obligatory_transfer=DODUO,RATTATA,CATERPIE,PIDGEY

# list of pokemon you always want to evolve before transfer to maximize XP
evolve_before_transfer=CATERPIE,RATTATA,WEEDLE,PIDGEY

# The stack of evolves needed to pop lucky egg and evolve all
evolve_stack_limit=100

# Use lucky egg before transfer (1 = yes, anything else = no)
use_lucky_egg=1

# Port where the socketserver should listen, 0 = do not listen
gui_port_socket=8001

# Export player/pokemondata on Profile Update. Options are:
#   *empty*  Don't export (default)
#   CSV      Correct USA/UK CSV format ("," as delimiter and "." as decimal separator)
#   DSV      European CSV/DSV format (";" as delimiter and "," as decimal separator)
#              Use this one if your MS Excel can't handle the default CSV option
#   JSON     JSON format
export=

# Initial map size (S2 tiles) to fetch (max. 9: ~3*3km area)
initial_map_size=9

# For artificial pauses/rests
# Chance to wait randomly at a pokestop in %, recommended about 10 or less, default disabled
wait_chance=0.0

# Time to wait in seconds, recommended 5-30, default disabled
wait_time_min=0
wait_time_max=0

# List of pokemon names
#MISSINGNO
#BULBASAUR
#IVYSAUR
#VENUSAUR
#CHARMANDER
#CHARMELEON
#CHARIZARD
#SQUIRTLE
#WARTORTLE
#BLASTOISE
#CATERPIE
#METAPOD
#BUTTERFREE
#WEEDLE
#KAKUNA
#BEEDRILL
#PIDGEY
#PIDGEOTTO
#PIDGEOT
#RATTATA
#RATICATE
#SPEAROW
#FEAROW
#EKANS
#ARBOK
#PIKACHU
#RAICHU
#SANDSHREW
#SANDSLASH
#NIDORAN_FEMALE
#NIDORINA
#NIDOQUEEN
#NIDORAN_MALE
#NIDORINO
#NIDOKING
#CLEFAIRY
#CLEFABLE
#VULPIX
#NINETALES
#JIGGLYPUFF
#WIGGLYTUFF
#ZUBAT
#GOLBAT
#ODDISH
#GLOOM
#VILEPLUME
#PARAS
#PARASECT
#VENONAT
#VENOMOTH
#DIGLETT
#DUGTRIO
#MEOWTH
#PERSIAN
#PSYDUCK
#GOLDUCK
#MANKEY
#PRIMEAPE
#GROWLITHE
#ARCANINE
#POLIWAG
#POLIWHIRL
#POLIWRATH
#ABRA
#KADABRA
#ALAKAZAM
#MACHOP
#MACHOKE
#MACHAMP
#BELLSPROUT
#WEEPINBELL
#VICTREEBEL
#TENTACOOL
#TENTACRUEL
#GEODUDE
#GRAVELER
#GOLEM
#PONYTA
#RAPIDASH
#SLOWPOKE
#SLOWBRO
#MAGNEMITE
#MAGNETON
#FARFETCHD
#DODUO
#DODRIO
#SEEL
#DEWGONG
#GRIMER
#MUK
#SHELLDER
#CLOYSTER
#GASTLY
#HAUNTER
#GENGAR
#ONIX
#DROWZEE
#HYPNO
#KRABBY
#KINGLER
#VOLTORB
#ELECTRODE
#EXEGGCUTE
#EXEGGUTOR
#CUBONE
#MAROWAK
#HITMONLEE
#HITMONCHAN
#LICKITUNG
#KOFFING
#WEEZING
#RHYHORN
#RHYDON
#CHANSEY
#TANGELA
#KANGASKHAN
#HORSEA
#SEADRA
#GOLDEEN
#SEAKING
#STARYU
#STARMIE
#MR_MIME
#SCYTHER
#JYNX
#ELECTABUZZ
#MAGMAR
#PINSIR
#TAUROS
#MAGIKARP
#GYARADOS
#LAPRAS
#DITTO
#EEVEE
#VAPOREON
#JOLTEON
#FLAREON
#PORYGON
#OMANYTE
#OMASTAR
#KABUTO
#KABUTOPS
#AERODACTYL
#SNORLAX
#ARTICUNO
#ZAPDOS
#MOLTRES
#DRATINI
#DRAGONAIR
#DRAGONITE
#MEWTWO
#MEW
`

 

Expected behavior:  The bot should find pokestop and walk to it

Actual behavior:  Bot doesn t find any pokestop, if I just keep the java file and the config file (removing all other files) the same thing happen

Stacktrace (If it's a crash): 
05 Oct 21:29:41 [default] - Getting map of (41.385057189360005, 2.1734345939101507)
05 Oct 21:29:41 [default] - Getting initial pokestops...
05 Oct 21:29:42 [default] - Got 0 pokestops
05 Oct 21:29:42 [default] - Retrying in 10 seconds...
05 Oct 21:29:52 [default] - Got 0 pokestops
05 Oct 21:29:52 [default] - Retrying in 10 seconds...


Version: 0.6.0

Operating System: Ubuntu 16.04

Java version:
 openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Leave this sentence in your issue as proof that you have read and used this template.
Contact GitHub

**Comment by Cypherke** [comment] 2016-10-06 14:34
dont use openjdk
